********************************************************************************
********************************************************************************
* Project: Policy and Fertility
* Owner: Kimberly McErlean
* Started: October 2024
* File: impute_couple_data
********************************************************************************
********************************************************************************

********************************************************************************
* Description
********************************************************************************
* This files imputes the individual level data (for off survey yeras primarily)
* Then matches partner's imputed characteristics

********************************************************************************
* Final prep for imputation
********************************************************************************
use "$created_data/PSID_couple_births_shared.dta", clear

inspect weekly_hrs_t_focal weekly_hrs_t1_focal weekly_hrs_t2_focal  housework_focal housework_t1_focal housework_t2_focal
browse unique_id partner_id survey_yr rel_start_yr relationship_duration in_sample weekly_hrs_t_focal weekly_hrs_t1_focal weekly_hrs_t2_focal  housework_focal housework_t1_focal housework_t2_focal
// okay, one problem with doing here is that I haven't yet matched partner data. Do I need to do that first?

// add in indicator of birth in year (to use in imputation) - but remember KIM this is not yet restricted sample (though I do have those flags)
sort unique_id partner_id survey_yr
browse unique_id partner_id survey_yr SEX shared_birth1_refyr shared_birth2_refyr shared_birth3_refyr shared_birth1_spyr shared_birth2_spyr shared_birth3_spyr

gen shared_birth_in_yr=0
forvalues b=1/9{
	replace shared_birth_in_yr = 1 if survey_yr == shared_birth`b'_refyr & SEX==2 // prioritize women's reports
	replace shared_birth_in_yr = 1 if survey_yr == shared_birth`b'_spyr & SEX==1
}

tab shared_birth_in_yr, m
browse unique_id partner_id survey_yr rel_start_yr SEX shared_birth_in_yr shared_birth1_refyr shared_birth2_refyr shared_birth3_refyr shared_birth1_spyr shared_birth2_spyr shared_birth3_spyr

// going to reshape on duration instead of survey yr so only keep people after the relationship
gen total_rel_dur = rel_end_all - rel_start_all if rel_end_all < 9000
replace total_rel_dur = last_couple_yr - rel_start_all if rel_end_all== 9998 | rel_end_all== 9999

by unique_id partner_id: egen max_dur = max(relationship_duration)
by unique_id partner_id: egen min_dur = min(relationship_duration)

tab relationship_duration, m
tab relationship_duration shared_birth_in_yr, row m // cutting off after 20 years because likelihood of birth declines
tab relationship_duration shared_birth_in_yr, col m // cutting off after 20 years because likelihood of birth declines
drop if relationship_duration > 15 // 20 causing some issues with imputation

// other checks
inspect housework_focal weekly_hrs_t_focal earnings_t_focal 
inspect housework_focal weekly_hrs_t_focal earnings_t_focal if in_sample==1 & survey_yr!=last_survey_yr // are some of these missings bc not in sample? In theory, work variables should not be missing. that doesn't explain all of it. should some of these be ZEROES and not missing? (based on employment status - but that is point in time...) should I update to 0s? but could have worked at other parts of the year.

browse unique_id survey_yr first_survey_yr last_survey_yr age_focal in_sample housework_focal employed_focal weekly_hrs_t_focal earnings_t_focal weekly_hrs_t1_focal earnings_t1_focal // so some are 0s. Some appear to be off years that I couldn't get data for (because corresponds to off year where they then have no more data following) OH and a bunch are 2021 because all of the data is t-1, so no data available yet. okay, yes ignoring 2021 / last survey yr helps reduce the missing

tabstat weekly_hrs_t_focal earnings_t_focal, by(employed_focal)
inspect weekly_hrs_t_focal earnings_t_focal if employed_focal==0
inspect weekly_hrs_t_focal earnings_t_focal if employed_focal==1

********************************************************************************
* Reshape wide for imputation
********************************************************************************
// This will now create variables outside of the bounds of the relationship, but I will drop later once imputed
// this is where I am confusing myself - because some of these people might be in the survey outside of the years of their relationship, but nw, I am assuming that info is missing, so do I actually need to pull in the records if they exist outside of their relationship? by doing what I did for UKHLS and using some sort of flag based on being in a couple? Or does this matter less because I am going to drop them outside the bounds of their relationship? I wonder if instead of doing this, I need to center on relationship duration and just keep a certain number of relationship durations? this might be better?

local fixed "SEX MARITAL_STATUS num_bio_kids_husb num_bio_kids_wife NUM_BIRTHS first_survey_yr last_survey_yr all_births_shared any_births_pre_rel any_shared_births birth_yr cah_birth_order* cah_child_birth_mon* cah_child_birth_yr* cah_event_type* cah_num_adoptive_kids_ref cah_num_adoptive_kids_sp cah_num_bio_kids_ref cah_num_bio_kids_sp cah_sharedchild* cah_unique_id_child* cah_unique_id_dad* cah_unique_id_mom* cluster coh1_end coh1_start coh2_end coh2_start coh3_end coh3_start ever_birth_husb ever_birth_wife FIRST_BIRTH_YR first_educ_focal FIRST_MARRIAGE_STATUS FIRST_MARRIAGE_YR_END FIRST_MARRIAGE_YR_START FIRST_SEPARATE_YR has_psid_gene hh1_end hh1_start hh2_end hh2_start hh3_end hh3_start hh4_end hh4_start hh5_end hh5_start IN_UNIT joint_first_birth joint_first_birth_alt joint_first_birth_rel joint_first_birth_timing joint_first_birth_yr joint_second_birth_opt1 joint_second_birth_opt2 joint_second_birth_opt3 joint_second_birth_timing joint_second_birth_yr last_race_focal later_first_birth later_first_birth_timing later_first_birth_yr main_fam_id main_per_id marr1_end marr1_start marr2_end marr2_start marr3_end marr3_start marr4_end marr4_start marr5_end marr5_start max_educ_focal mh_status* mh_yr_end* mh_yr_married* num_births_pre_indv_ref num_births_pre_indv_sp num_births_pre_ref num_births_pre_sp NUM_MARRIED num_shared_births_ref num_shared_births_sp permanent_attrit pre_rel_birth_husb pre_rel_birth_wife raceth_fixed_focal RECENT_MARRIAGE_STATUS RECENT_MARRIAGE_YR_END RECENT_MARRIAGE_YR_START RECENT_SEPARATE_YR rel_start_all rel_end_all rel1_end rel1_start rel2_end rel2_start rel3_end rel3_start rel4_end rel4_start rel5_end rel5_start SAMPLE SAMPLE_STATUS_TYPE sample_type shared_birth*_refid shared_birth*_refyr shared_birth*_spid shared_birth*_spyr shared_first_birth shared_first_birth_timing shared_first_birth_yr shared_second_birth shared_second_birth_timing shared_second_birth_yr stratum YR_NONRESPONSE_FIRST YR_NONRESPONSE_RECENT total_rel_dur max_dur min_dur"

local timevary "partnered raceth_focal any_psid_births_t_focal any_psid_births_t_hh any_psid_births_t1_focal any_psid_births_t1_hh FAMILY_INTERVIEW_NUM_ state_fips age_focal AGE_YOUNG_CHILD_ children cohab_est_head college_focal COR_IMM_WT_ CORE_WEIGHT_ COUPLE_STATUS_HEAD_ CROSS_SECTION_FAM_WT_ CROSS_SECTION_WT_ earnings_t_focal earnings_t1_focal earnings_t2_focal educ_focal educ_t1_focal educ_t2_focal employed_focal employed_t1_earn_focal employed_t1_hrs_focal employed_t2_focal first_birth_sample_flag HOUSE_STATUS_ housework_focal housework_t1_focal housework_t2_focal in_sample LONG_WT_ MARITAL_PAIRS_ marital_status_updated MARST_DEFACTO_HEAD_ MARST_LEGAL_HEAD_ moved MOVED_YEAR_ NUM_CHILDREN_ NUM_IN_HH_ rel_status RELATION_ survey_yr relationship_est religion_focal religion_t1_focal religion_t2_focal second_birth_sample_flag second_birth_flag_cons structural_familism TOTAL_INCOME_T_FAMILY TOTAL_INCOME_T1_FAMILY_ TOTAL_INCOME_T2_FAMILY_ weekly_hrs_t_focal weekly_hrs_t1_focal weekly_hrs_t2_focal shared_birth_in_yr"

keep unique_id partner_id relationship_duration `fixed' `timevary'

reshape wide `timevary', i(unique_id partner_id) j(relationship_duration)

// actually can update the shared birth in year indicator
forvalues d=0/15{
	gen shared_birth_in_yr`d'_v2=0
		
	forvalues b=1/9{
		replace shared_birth_in_yr`d'_v2 = 1 if survey_yr`d' == shared_birth`b'_refyr & SEX==2 & survey_yr`d'!=.
		replace shared_birth_in_yr`d'_v2 = 1 if survey_yr`d' == shared_birth`b'_spyr & SEX==1 & survey_yr`d'!=.
	}
}

// tab shared_birth_in_yr1_v2 shared_birth_in_yr1, m
// browse shared_birth_in_yr1_v2 survey_yr1 shared_birth*_refyr

forvalues d=0/15{
	replace partnered`d' = 0 if partnered`d'==. // not in this relationshipship
}

// add some better variables
drop first_educ_focal
egen first_educ_focal = rowfirst(educ_focal*)
label values first_educ_focal educ
browse unique_id first_educ_focal max_educ_focal educ_focal*

tab first_educ_focal,m
tab max_educ_focal, m

egen last_religion_focal = rowlast(religion_focal*)
egen first_religion_focal = rowfirst(religion_focal*)
label values last_religion_focal first_religion_focal religion
browse unique_id partner_id first_religion_focal last_religion_focal max_dur religion_focal*

forvalues d=0/15{
	gen religion_imp_focal`d'= religion_focal`d'
	replace religion_imp_focal`d' = last_religion_focal if religion_imp_focal`d'==. & `d' > max_dur
	replace religion_imp_focal`d' = first_religion_focal if religion_imp_focal`d'==. & `d' < min_dur
	label values religion_imp_focal`d' religion
}

browse unique_id partner_id first_religion_focal last_religion_focal min_dur max_dur religion_imp_focal* religion_focal*

// clean up data
drop if raceth_fixed_focal==. // for now, just so this is actually complete
drop if birth_yr==. | birth_yr==9999 // so complete
drop if first_educ_focal==.

save "$temp/PSID_couples_wide_toimpute.dta", replace

browse unique_id partner_id min_dur max_dur weekly_hrs_t1_focal*

********************************************************************************
**# Imputation
********************************************************************************
egen nmis_shared = rmiss(shared_birth_in_yr*_v2)
tab nmis_shared, m

egen nmis_partner = rmiss(partnered*)
tab nmis_partner, m

mi set wide
mi register imputed weekly_hrs_t_focal* weekly_hrs_t1_focal* housework_focal* housework_t1_focal* earnings_t_focal* earnings_t1_focal* TOTAL_INCOME_T_FAMILY* TOTAL_INCOME_T1_FAMILY* NUM_CHILDREN_*  // religion_imp_focal* religion_t1_focal*
mi register regular SEX birth_yr raceth_fixed_focal max_educ_focal sample_type rel_start_all FIRST_BIRTH_YR shared_birth_in_yr*_v2 partnered*

#delimit ;

mi impute chained

/* work hours t */
(pmm, knn(5) include (           weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t1_focal0 housework_focal0 housework_t1_focal0 earnings_t_focal0 earnings_t1_focal0 TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T1_FAMILY_0 NUM_CHILDREN_0 i.shared_birth_in_yr0_v2 i.partnered0)) weekly_hrs_t_focal0
(pmm, knn(5) include (          weekly_hrs_t_focal0 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t1_focal1 housework_focal1 housework_t1_focal1 earnings_t_focal1 earnings_t1_focal1 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T1_FAMILY_1 NUM_CHILDREN_1 i.shared_birth_in_yr1_v2 i.partnered1)) weekly_hrs_t_focal1
(pmm, knn(5) include (         weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t1_focal2 housework_focal2 housework_t1_focal2 earnings_t_focal2 earnings_t1_focal2 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T1_FAMILY_2 NUM_CHILDREN_2 i.shared_birth_in_yr2_v2 i.partnered2)) weekly_hrs_t_focal2
(pmm, knn(5) include (        weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t1_focal3 housework_focal3 housework_t1_focal3 earnings_t_focal3 earnings_t1_focal3 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T1_FAMILY_3 NUM_CHILDREN_3 i.shared_birth_in_yr3_v2 i.partnered3)) weekly_hrs_t_focal3
(pmm, knn(5) include (       weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal14 weekly_hrs_t1_focal4 housework_focal4 housework_t1_focal4 earnings_t_focal4 earnings_t1_focal4 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T1_FAMILY_4 NUM_CHILDREN_4 i.shared_birth_in_yr4_v2 i.partnered4)) weekly_hrs_t_focal4
(pmm, knn(5) include (      weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal14 weekly_hrs_t_focal15 weekly_hrs_t1_focal5 housework_focal5 housework_t1_focal5 earnings_t_focal5 earnings_t1_focal5 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T1_FAMILY_5 NUM_CHILDREN_5 i.shared_birth_in_yr5_v2 i.partnered5)) weekly_hrs_t_focal5
(pmm, knn(5) include (     weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal14 weekly_hrs_t_focal15  weekly_hrs_t1_focal6 housework_focal6 housework_t1_focal6 earnings_t_focal6 earnings_t1_focal6 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T1_FAMILY_6 NUM_CHILDREN_6 i.shared_birth_in_yr6_v2 i.partnered6)) weekly_hrs_t_focal6
(pmm, knn(5) include (    weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal14 weekly_hrs_t_focal15   weekly_hrs_t1_focal7 housework_focal7 housework_t1_focal7 earnings_t_focal7 earnings_t1_focal7 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T1_FAMILY_7 NUM_CHILDREN_7 i.shared_birth_in_yr7_v2 i.partnered7)) weekly_hrs_t_focal7
(pmm, knn(5) include (   weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal14 weekly_hrs_t_focal15    weekly_hrs_t1_focal8 housework_focal8 housework_t1_focal8 earnings_t_focal8 earnings_t1_focal8 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T1_FAMILY_8 NUM_CHILDREN_8 i.shared_birth_in_yr8_v2 i.partnered8)) weekly_hrs_t_focal8
(pmm, knn(5) include (  weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal14 weekly_hrs_t_focal15     weekly_hrs_t1_focal9 housework_focal9 housework_t1_focal9 earnings_t_focal9 earnings_t1_focal9 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T1_FAMILY_9 NUM_CHILDREN_9 i.shared_birth_in_yr9_v2 i.partnered9)) weekly_hrs_t_focal9
(pmm, knn(5) include ( weekly_hrs_t_focal0 weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal14 weekly_hrs_t_focal15      weekly_hrs_t1_focal10 housework_focal10 housework_t1_focal10 earnings_t_focal10 earnings_t1_focal10 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T1_FAMILY_10 NUM_CHILDREN_10 i.shared_birth_in_yr10_v2 i.partnered10)) weekly_hrs_t_focal10
(pmm, knn(5) include ( weekly_hrs_t_focal1 weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal14 weekly_hrs_t_focal15       weekly_hrs_t1_focal11 housework_focal11 housework_t1_focal11 earnings_t_focal11 earnings_t1_focal11 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T1_FAMILY_11 NUM_CHILDREN_11 i.shared_birth_in_yr11_v2 i.partnered11)) weekly_hrs_t_focal11
(pmm, knn(5) include ( weekly_hrs_t_focal2 weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal13 weekly_hrs_t_focal14 weekly_hrs_t_focal15        weekly_hrs_t1_focal12 housework_focal12 housework_t1_focal12 earnings_t_focal12 earnings_t1_focal12 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T1_FAMILY_12 NUM_CHILDREN_12 i.shared_birth_in_yr12_v2 i.partnered12)) weekly_hrs_t_focal12
(pmm, knn(5) include ( weekly_hrs_t_focal3 weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal14 weekly_hrs_t_focal15         weekly_hrs_t1_focal13 housework_focal13 housework_t1_focal13 earnings_t_focal13 earnings_t1_focal13 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T1_FAMILY_13 NUM_CHILDREN_13 i.shared_birth_in_yr13_v2 i.partnered13)) weekly_hrs_t_focal13
(pmm, knn(5) include ( weekly_hrs_t_focal4 weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal15          weekly_hrs_t1_focal14 housework_focal14 housework_t1_focal14 earnings_t_focal14 earnings_t1_focal14 TOTAL_INCOME_T_FAMILY14 TOTAL_INCOME_T1_FAMILY_14 NUM_CHILDREN_14 i.shared_birth_in_yr14_v2 i.partnered14)) weekly_hrs_t_focal14
(pmm, knn(5) include ( weekly_hrs_t_focal5 weekly_hrs_t_focal6 weekly_hrs_t_focal7 weekly_hrs_t_focal8 weekly_hrs_t_focal9 weekly_hrs_t_focal10 weekly_hrs_t_focal11 weekly_hrs_t_focal12 weekly_hrs_t_focal13 weekly_hrs_t_focal14           weekly_hrs_t1_focal15 housework_focal15 housework_t1_focal15 earnings_t_focal15 earnings_t1_focal15 TOTAL_INCOME_T_FAMILY15 TOTAL_INCOME_T1_FAMILY_15 NUM_CHILDREN_15 i.shared_birth_in_yr15_v2 i.partnered15)) weekly_hrs_t_focal15


/* work hours t1 */
(pmm, knn(5) include (           weekly_hrs_t1_focal1 weekly_hrs_t1_focal2 weekly_hrs_t1_focal3 weekly_hrs_t1_focal4 weekly_hrs_t1_focal5 weekly_hrs_t1_focal6 weekly_hrs_t1_focal7 weekly_hrs_t1_focal8 weekly_hrs_t1_focal9 weekly_hrs_t1_focal10 weekly_hrs_t_focal0 housework_focal0 housework_t1_focal0 earnings_t_focal0 earnings_t1_focal0 TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T1_FAMILY_0 NUM_CHILDREN_0 i.shared_birth_in_yr0_v2 i.partnered0)) weekly_hrs_t1_focal0
(pmm, knn(5) include (          weekly_hrs_t1_focal0 weekly_hrs_t1_focal2 weekly_hrs_t1_focal3 weekly_hrs_t1_focal4 weekly_hrs_t1_focal5 weekly_hrs_t1_focal6 weekly_hrs_t1_focal7 weekly_hrs_t1_focal8 weekly_hrs_t1_focal9 weekly_hrs_t1_focal10 weekly_hrs_t1_focal11 weekly_hrs_t_focal1 housework_focal1 housework_t1_focal1 earnings_t_focal1 earnings_t1_focal1 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T1_FAMILY_1 NUM_CHILDREN_1 i.shared_birth_in_yr1_v2 i.partnered1)) weekly_hrs_t1_focal1
(pmm, knn(5) include (         weekly_hrs_t1_focal0 weekly_hrs_t1_focal1 weekly_hrs_t1_focal3 weekly_hrs_t1_focal4 weekly_hrs_t1_focal5 weekly_hrs_t1_focal6 weekly_hrs_t1_focal7 weekly_hrs_t1_focal8 weekly_hrs_t1_focal9 weekly_hrs_t1_focal10 weekly_hrs_t1_focal11 weekly_hrs_t1_focal12 weekly_hrs_t_focal2 housework_focal2 housework_t1_focal2 earnings_t_focal2 earnings_t1_focal2 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T1_FAMILY_2 NUM_CHILDREN_2 i.shared_birth_in_yr2_v2 i.partnered2)) weekly_hrs_t1_focal2
(pmm, knn(5) include (        weekly_hrs_t1_focal0 weekly_hrs_t1_focal1 weekly_hrs_t1_focal2 weekly_hrs_t1_focal4 weekly_hrs_t1_focal5 weekly_hrs_t1_focal6 weekly_hrs_t1_focal7 weekly_hrs_t1_focal8 weekly_hrs_t1_focal9 weekly_hrs_t1_focal10 weekly_hrs_t1_focal11 weekly_hrs_t1_focal12 weekly_hrs_t1_focal13 weekly_hrs_t_focal3 housework_focal3 housework_t1_focal3 earnings_t_focal3 earnings_t1_focal3 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T1_FAMILY_3 NUM_CHILDREN_3 i.shared_birth_in_yr3_v2 i.partnered3)) weekly_hrs_t1_focal3
(pmm, knn(5) include (       weekly_hrs_t1_focal0 weekly_hrs_t1_focal1 weekly_hrs_t1_focal2 weekly_hrs_t1_focal3 weekly_hrs_t1_focal5 weekly_hrs_t1_focal6 weekly_hrs_t1_focal7 weekly_hrs_t1_focal8 weekly_hrs_t1_focal9 weekly_hrs_t1_focal10 weekly_hrs_t1_focal11 weekly_hrs_t1_focal12 weekly_hrs_t1_focal13 weekly_hrs_t1_focal14 weekly_hrs_t_focal4 housework_focal4 housework_t1_focal4 earnings_t_focal4 earnings_t1_focal4 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T1_FAMILY_4 NUM_CHILDREN_4 i.shared_birth_in_yr4_v2 i.partnered4)) weekly_hrs_t1_focal4
(pmm, knn(5) include (      weekly_hrs_t1_focal0 weekly_hrs_t1_focal1 weekly_hrs_t1_focal2 weekly_hrs_t1_focal3 weekly_hrs_t1_focal4 weekly_hrs_t1_focal6 weekly_hrs_t1_focal7 weekly_hrs_t1_focal8 weekly_hrs_t1_focal9 weekly_hrs_t1_focal10 weekly_hrs_t1_focal11 weekly_hrs_t1_focal12 weekly_hrs_t1_focal13 weekly_hrs_t1_focal14 weekly_hrs_t1_focal15 weekly_hrs_t_focal5 housework_focal5 housework_t1_focal5 earnings_t_focal5 earnings_t1_focal5 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T1_FAMILY_5 NUM_CHILDREN_5 i.shared_birth_in_yr5_v2 i.partnered5)) weekly_hrs_t1_focal5
(pmm, knn(5) include (     weekly_hrs_t1_focal0 weekly_hrs_t1_focal1 weekly_hrs_t1_focal2 weekly_hrs_t1_focal3 weekly_hrs_t1_focal4 weekly_hrs_t1_focal5 weekly_hrs_t1_focal7 weekly_hrs_t1_focal8 weekly_hrs_t1_focal9 weekly_hrs_t1_focal10 weekly_hrs_t1_focal11 weekly_hrs_t1_focal12 weekly_hrs_t1_focal13 weekly_hrs_t1_focal14 weekly_hrs_t1_focal15  weekly_hrs_t_focal6 housework_focal6 housework_t1_focal6 earnings_t_focal6 earnings_t1_focal6 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T1_FAMILY_6 NUM_CHILDREN_6 i.shared_birth_in_yr6_v2 i.partnered6)) weekly_hrs_t1_focal6
(pmm, knn(5) include (    weekly_hrs_t1_focal0 weekly_hrs_t1_focal1 weekly_hrs_t1_focal2 weekly_hrs_t1_focal3 weekly_hrs_t1_focal4 weekly_hrs_t1_focal5 weekly_hrs_t1_focal6 weekly_hrs_t1_focal8 weekly_hrs_t1_focal9 weekly_hrs_t1_focal10 weekly_hrs_t1_focal11 weekly_hrs_t1_focal12 weekly_hrs_t1_focal13 weekly_hrs_t1_focal14 weekly_hrs_t1_focal15   weekly_hrs_t_focal7 housework_focal7 housework_t1_focal7 earnings_t_focal7 earnings_t1_focal7 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T1_FAMILY_7 NUM_CHILDREN_7 i.shared_birth_in_yr7_v2 i.partnered7)) weekly_hrs_t1_focal7
(pmm, knn(5) include (   weekly_hrs_t1_focal0 weekly_hrs_t1_focal1 weekly_hrs_t1_focal2 weekly_hrs_t1_focal3 weekly_hrs_t1_focal4 weekly_hrs_t1_focal5 weekly_hrs_t1_focal6 weekly_hrs_t1_focal7 weekly_hrs_t1_focal9 weekly_hrs_t1_focal10 weekly_hrs_t1_focal11 weekly_hrs_t1_focal12 weekly_hrs_t1_focal13 weekly_hrs_t1_focal14 weekly_hrs_t1_focal15    weekly_hrs_t_focal8 housework_focal8 housework_t1_focal8 earnings_t_focal8 earnings_t1_focal8 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T1_FAMILY_8 NUM_CHILDREN_8 i.shared_birth_in_yr8_v2 i.partnered8)) weekly_hrs_t1_focal8
(pmm, knn(5) include (  weekly_hrs_t1_focal0 weekly_hrs_t1_focal1 weekly_hrs_t1_focal2 weekly_hrs_t1_focal3 weekly_hrs_t1_focal4 weekly_hrs_t1_focal5 weekly_hrs_t1_focal6 weekly_hrs_t1_focal7 weekly_hrs_t1_focal8 weekly_hrs_t1_focal10 weekly_hrs_t1_focal11 weekly_hrs_t1_focal12 weekly_hrs_t1_focal13 weekly_hrs_t1_focal14 weekly_hrs_t1_focal15     weekly_hrs_t_focal9 housework_focal9 housework_t1_focal9 earnings_t_focal9 earnings_t1_focal9 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T1_FAMILY_9 NUM_CHILDREN_9 i.shared_birth_in_yr9_v2 i.partnered9)) weekly_hrs_t1_focal9
(pmm, knn(5) include ( weekly_hrs_t1_focal0 weekly_hrs_t1_focal1 weekly_hrs_t1_focal2 weekly_hrs_t1_focal3 weekly_hrs_t1_focal4 weekly_hrs_t1_focal5 weekly_hrs_t1_focal6 weekly_hrs_t1_focal7 weekly_hrs_t1_focal8 weekly_hrs_t1_focal9 weekly_hrs_t1_focal11 weekly_hrs_t1_focal12 weekly_hrs_t1_focal13 weekly_hrs_t1_focal14 weekly_hrs_t1_focal15      weekly_hrs_t_focal10 housework_focal10 housework_t1_focal10 earnings_t_focal10 earnings_t1_focal10 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T1_FAMILY_10 NUM_CHILDREN_10 i.shared_birth_in_yr10_v2 i.partnered10)) weekly_hrs_t1_focal10
(pmm, knn(5) include ( weekly_hrs_t1_focal1 weekly_hrs_t1_focal2 weekly_hrs_t1_focal3 weekly_hrs_t1_focal4 weekly_hrs_t1_focal5 weekly_hrs_t1_focal6 weekly_hrs_t1_focal7 weekly_hrs_t1_focal8 weekly_hrs_t1_focal9 weekly_hrs_t1_focal10 weekly_hrs_t1_focal12 weekly_hrs_t1_focal13 weekly_hrs_t1_focal14 weekly_hrs_t1_focal15       weekly_hrs_t_focal11 housework_focal11 housework_t1_focal11 earnings_t_focal11 earnings_t1_focal11 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T1_FAMILY_11 NUM_CHILDREN_11 i.shared_birth_in_yr11_v2 i.partnered11)) weekly_hrs_t1_focal11
(pmm, knn(5) include ( weekly_hrs_t1_focal2 weekly_hrs_t1_focal3 weekly_hrs_t1_focal4 weekly_hrs_t1_focal5 weekly_hrs_t1_focal6 weekly_hrs_t1_focal7 weekly_hrs_t1_focal8 weekly_hrs_t1_focal9 weekly_hrs_t1_focal10 weekly_hrs_t1_focal11 weekly_hrs_t1_focal13 weekly_hrs_t1_focal14 weekly_hrs_t1_focal15        weekly_hrs_t_focal12 housework_focal12 housework_t1_focal12 earnings_t_focal12 earnings_t1_focal12 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T1_FAMILY_12 NUM_CHILDREN_12 i.shared_birth_in_yr12_v2 i.partnered12)) weekly_hrs_t1_focal12
(pmm, knn(5) include ( weekly_hrs_t1_focal3 weekly_hrs_t1_focal4 weekly_hrs_t1_focal5 weekly_hrs_t1_focal6 weekly_hrs_t1_focal7 weekly_hrs_t1_focal8 weekly_hrs_t1_focal9 weekly_hrs_t1_focal10 weekly_hrs_t1_focal11 weekly_hrs_t1_focal12 weekly_hrs_t1_focal14 weekly_hrs_t1_focal15         weekly_hrs_t_focal13 housework_focal13 housework_t1_focal13 earnings_t_focal13 earnings_t1_focal13 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T1_FAMILY_13 NUM_CHILDREN_13 i.shared_birth_in_yr13_v2 i.partnered13)) weekly_hrs_t1_focal13
(pmm, knn(5) include ( weekly_hrs_t1_focal4 weekly_hrs_t1_focal5 weekly_hrs_t1_focal6 weekly_hrs_t1_focal7 weekly_hrs_t1_focal8 weekly_hrs_t1_focal9 weekly_hrs_t1_focal10 weekly_hrs_t1_focal11 weekly_hrs_t1_focal12 weekly_hrs_t1_focal13 weekly_hrs_t1_focal15          weekly_hrs_t_focal14 housework_focal14 housework_t1_focal14 earnings_t_focal14 earnings_t1_focal14 TOTAL_INCOME_T_FAMILY14 TOTAL_INCOME_T1_FAMILY_14 NUM_CHILDREN_14 i.shared_birth_in_yr14_v2 i.partnered14)) weekly_hrs_t1_focal14
(pmm, knn(5) include ( weekly_hrs_t1_focal5 weekly_hrs_t1_focal6 weekly_hrs_t1_focal7 weekly_hrs_t1_focal8 weekly_hrs_t1_focal9 weekly_hrs_t1_focal10 weekly_hrs_t1_focal11 weekly_hrs_t1_focal12 weekly_hrs_t1_focal13 weekly_hrs_t1_focal14           weekly_hrs_t_focal15 housework_focal15 housework_t1_focal15 earnings_t_focal15 earnings_t1_focal15 TOTAL_INCOME_T_FAMILY15 TOTAL_INCOME_T1_FAMILY_15 NUM_CHILDREN_15 i.shared_birth_in_yr15_v2 i.partnered15)) weekly_hrs_t1_focal15


/* housework t */
(pmm, knn(5) include (           housework_focal1 housework_focal2 housework_focal3 housework_focal4 housework_focal5 housework_focal6 housework_focal7 housework_focal8 housework_focal9 housework_focal10 weekly_hrs_t1_focal0 weekly_hrs_t_focal0 housework_t1_focal0 earnings_t_focal0 earnings_t1_focal0 TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T1_FAMILY_0 NUM_CHILDREN_0 i.shared_birth_in_yr0_v2 i.partnered0)) housework_focal0
(pmm, knn(5) include (          housework_focal0 housework_focal2 housework_focal3 housework_focal4 housework_focal5 housework_focal6 housework_focal7 housework_focal8 housework_focal9 housework_focal10 housework_focal11 weekly_hrs_t1_focal1 weekly_hrs_t_focal1 housework_t1_focal1 earnings_t_focal1 earnings_t1_focal1 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T1_FAMILY_1 NUM_CHILDREN_1 i.shared_birth_in_yr1_v2 i.partnered1)) housework_focal1
(pmm, knn(5) include (         housework_focal0 housework_focal1 housework_focal3 housework_focal4 housework_focal5 housework_focal6 housework_focal7 housework_focal8 housework_focal9 housework_focal10 housework_focal11 housework_focal12 weekly_hrs_t1_focal2 weekly_hrs_t_focal2 housework_t1_focal2 earnings_t_focal2 earnings_t1_focal2 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T1_FAMILY_2 NUM_CHILDREN_2 i.shared_birth_in_yr2_v2 i.partnered2)) housework_focal2
(pmm, knn(5) include (        housework_focal0 housework_focal1 housework_focal2 housework_focal4 housework_focal5 housework_focal6 housework_focal7 housework_focal8 housework_focal9 housework_focal10 housework_focal11 housework_focal12 housework_focal13 weekly_hrs_t1_focal3 weekly_hrs_t_focal3 housework_t1_focal3 earnings_t_focal3 earnings_t1_focal3 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T1_FAMILY_3 NUM_CHILDREN_3 i.shared_birth_in_yr3_v2 i.partnered3)) housework_focal3
(pmm, knn(5) include (       housework_focal0 housework_focal1 housework_focal2 housework_focal3 housework_focal5 housework_focal6 housework_focal7 housework_focal8 housework_focal9 housework_focal10 housework_focal11 housework_focal12 housework_focal13 housework_focal14 weekly_hrs_t1_focal4 weekly_hrs_t_focal4 housework_t1_focal4 earnings_t_focal4 earnings_t1_focal4 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T1_FAMILY_4 NUM_CHILDREN_4 i.shared_birth_in_yr4_v2 i.partnered4)) housework_focal4
(pmm, knn(5) include (      housework_focal0 housework_focal1 housework_focal2 housework_focal3 housework_focal4 housework_focal6 housework_focal7 housework_focal8 housework_focal9 housework_focal10 housework_focal11 housework_focal12 housework_focal13 housework_focal14 housework_focal15 weekly_hrs_t1_focal5 weekly_hrs_t_focal5 housework_t1_focal5 earnings_t_focal5 earnings_t1_focal5 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T1_FAMILY_5 NUM_CHILDREN_5 i.shared_birth_in_yr5_v2 i.partnered5)) housework_focal5
(pmm, knn(5) include (     housework_focal0 housework_focal1 housework_focal2 housework_focal3 housework_focal4 housework_focal5 housework_focal7 housework_focal8 housework_focal9 housework_focal10 housework_focal11 housework_focal12 housework_focal13 housework_focal14 housework_focal15  weekly_hrs_t1_focal6 weekly_hrs_t_focal6 housework_t1_focal6 earnings_t_focal6 earnings_t1_focal6 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T1_FAMILY_6 NUM_CHILDREN_6 i.shared_birth_in_yr6_v2 i.partnered6)) housework_focal6
(pmm, knn(5) include (    housework_focal0 housework_focal1 housework_focal2 housework_focal3 housework_focal4 housework_focal5 housework_focal6 housework_focal8 housework_focal9 housework_focal10 housework_focal11 housework_focal12 housework_focal13 housework_focal14 housework_focal15   weekly_hrs_t1_focal7 weekly_hrs_t_focal7 housework_t1_focal7 earnings_t_focal7 earnings_t1_focal7 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T1_FAMILY_7 NUM_CHILDREN_7 i.shared_birth_in_yr7_v2 i.partnered7)) housework_focal7
(pmm, knn(5) include (   housework_focal0 housework_focal1 housework_focal2 housework_focal3 housework_focal4 housework_focal5 housework_focal6 housework_focal7 housework_focal9 housework_focal10 housework_focal11 housework_focal12 housework_focal13 housework_focal14 housework_focal15    weekly_hrs_t1_focal8 weekly_hrs_t_focal8 housework_t1_focal8 earnings_t_focal8 earnings_t1_focal8 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T1_FAMILY_8 NUM_CHILDREN_8 i.shared_birth_in_yr8_v2 i.partnered8)) housework_focal8
(pmm, knn(5) include (  housework_focal0 housework_focal1 housework_focal2 housework_focal3 housework_focal4 housework_focal5 housework_focal6 housework_focal7 housework_focal8 housework_focal10 housework_focal11 housework_focal12 housework_focal13 housework_focal14 housework_focal15     weekly_hrs_t1_focal9 weekly_hrs_t_focal9 housework_t1_focal9 earnings_t_focal9 earnings_t1_focal9 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T1_FAMILY_9 NUM_CHILDREN_9 i.shared_birth_in_yr9_v2 i.partnered9)) housework_focal9
(pmm, knn(5) include ( housework_focal0 housework_focal1 housework_focal2 housework_focal3 housework_focal4 housework_focal5 housework_focal6 housework_focal7 housework_focal8 housework_focal9 housework_focal11 housework_focal12 housework_focal13 housework_focal14 housework_focal15      weekly_hrs_t1_focal10 weekly_hrs_t_focal10 housework_t1_focal10 earnings_t_focal10 earnings_t1_focal10 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T1_FAMILY_10 NUM_CHILDREN_10 i.shared_birth_in_yr10_v2 i.partnered10)) housework_focal10
(pmm, knn(5) include ( housework_focal1 housework_focal2 housework_focal3 housework_focal4 housework_focal5 housework_focal6 housework_focal7 housework_focal8 housework_focal9 housework_focal10 housework_focal12 housework_focal13 housework_focal14 housework_focal15       weekly_hrs_t1_focal11 weekly_hrs_t_focal11 housework_t1_focal11 earnings_t_focal11 earnings_t1_focal11 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T1_FAMILY_11 NUM_CHILDREN_11 i.shared_birth_in_yr11_v2 i.partnered11)) housework_focal11
(pmm, knn(5) include ( housework_focal2 housework_focal3 housework_focal4 housework_focal5 housework_focal6 housework_focal7 housework_focal8 housework_focal9 housework_focal10 housework_focal11 housework_focal13 housework_focal14 housework_focal15        weekly_hrs_t1_focal12 weekly_hrs_t_focal12 housework_t1_focal12 earnings_t_focal12 earnings_t1_focal12 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T1_FAMILY_12 NUM_CHILDREN_12 i.shared_birth_in_yr12_v2 i.partnered12)) housework_focal12
(pmm, knn(5) include ( housework_focal3 housework_focal4 housework_focal5 housework_focal6 housework_focal7 housework_focal8 housework_focal9 housework_focal10 housework_focal11 housework_focal12 housework_focal14 housework_focal15         weekly_hrs_t1_focal13 weekly_hrs_t_focal13 housework_t1_focal13 earnings_t_focal13 earnings_t1_focal13 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T1_FAMILY_13 NUM_CHILDREN_13 i.shared_birth_in_yr13_v2 i.partnered13)) housework_focal13
(pmm, knn(5) include ( housework_focal4 housework_focal5 housework_focal6 housework_focal7 housework_focal8 housework_focal9 housework_focal10 housework_focal11 housework_focal12 housework_focal13 housework_focal15          weekly_hrs_t1_focal14 weekly_hrs_t_focal14 housework_t1_focal14 earnings_t_focal14 earnings_t1_focal14 TOTAL_INCOME_T_FAMILY14 TOTAL_INCOME_T1_FAMILY_14 NUM_CHILDREN_14 i.shared_birth_in_yr14_v2 i.partnered14)) housework_focal14
(pmm, knn(5) include ( housework_focal5 housework_focal6 housework_focal7 housework_focal8 housework_focal9 housework_focal10 housework_focal11 housework_focal12 housework_focal13 housework_focal14           weekly_hrs_t1_focal15 weekly_hrs_t_focal15 housework_t1_focal15 earnings_t_focal15 earnings_t1_focal15 TOTAL_INCOME_T_FAMILY15 TOTAL_INCOME_T1_FAMILY_15 NUM_CHILDREN_15 i.shared_birth_in_yr15_v2 i.partnered15)) housework_focal15


/* housework t1 */
(pmm, knn(5) include (           housework_t1_focal1 housework_t1_focal2 housework_t1_focal3 housework_t1_focal4 housework_t1_focal5 housework_t1_focal6 housework_t1_focal7 housework_t1_focal8 housework_t1_focal9 housework_t1_focal10 weekly_hrs_t1_focal0 weekly_hrs_t_focal0 housework_focal0 earnings_t_focal0 earnings_t1_focal0 TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T1_FAMILY_0 NUM_CHILDREN_0 i.shared_birth_in_yr0_v2 i.partnered0)) housework_t1_focal0
(pmm, knn(5) include (          housework_t1_focal0 housework_t1_focal2 housework_t1_focal3 housework_t1_focal4 housework_t1_focal5 housework_t1_focal6 housework_t1_focal7 housework_t1_focal8 housework_t1_focal9 housework_t1_focal10 housework_t1_focal11 weekly_hrs_t1_focal1 weekly_hrs_t_focal1 housework_focal1 earnings_t_focal1 earnings_t1_focal1 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T1_FAMILY_1 NUM_CHILDREN_1 i.shared_birth_in_yr1_v2 i.partnered1)) housework_t1_focal1
(pmm, knn(5) include (         housework_t1_focal0 housework_t1_focal1 housework_t1_focal3 housework_t1_focal4 housework_t1_focal5 housework_t1_focal6 housework_t1_focal7 housework_t1_focal8 housework_t1_focal9 housework_t1_focal10 housework_t1_focal11 housework_t1_focal12 weekly_hrs_t1_focal2 weekly_hrs_t_focal2 housework_focal2 earnings_t_focal2 earnings_t1_focal2 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T1_FAMILY_2 NUM_CHILDREN_2 i.shared_birth_in_yr2_v2 i.partnered2)) housework_t1_focal2
(pmm, knn(5) include (        housework_t1_focal0 housework_t1_focal1 housework_t1_focal2 housework_t1_focal4 housework_t1_focal5 housework_t1_focal6 housework_t1_focal7 housework_t1_focal8 housework_t1_focal9 housework_t1_focal10 housework_t1_focal11 housework_t1_focal12 housework_t1_focal13 weekly_hrs_t1_focal3 weekly_hrs_t_focal3 housework_focal3 earnings_t_focal3 earnings_t1_focal3 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T1_FAMILY_3 NUM_CHILDREN_3 i.shared_birth_in_yr3_v2 i.partnered3)) housework_t1_focal3
(pmm, knn(5) include (       housework_t1_focal0 housework_t1_focal1 housework_t1_focal2 housework_t1_focal3 housework_t1_focal5 housework_t1_focal6 housework_t1_focal7 housework_t1_focal8 housework_t1_focal9 housework_t1_focal10 housework_t1_focal11 housework_t1_focal12 housework_t1_focal13 housework_t1_focal14 weekly_hrs_t1_focal4 weekly_hrs_t_focal4 housework_focal4 earnings_t_focal4 earnings_t1_focal4 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T1_FAMILY_4 NUM_CHILDREN_4 i.shared_birth_in_yr4_v2 i.partnered4)) housework_t1_focal4
(pmm, knn(5) include (      housework_t1_focal0 housework_t1_focal1 housework_t1_focal2 housework_t1_focal3 housework_t1_focal4 housework_t1_focal6 housework_t1_focal7 housework_t1_focal8 housework_t1_focal9 housework_t1_focal10 housework_t1_focal11 housework_t1_focal12 housework_t1_focal13 housework_t1_focal14 housework_t1_focal15 weekly_hrs_t1_focal5 weekly_hrs_t_focal5 housework_focal5 earnings_t_focal5 earnings_t1_focal5 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T1_FAMILY_5 NUM_CHILDREN_5 i.shared_birth_in_yr5_v2 i.partnered5)) housework_t1_focal5
(pmm, knn(5) include (     housework_t1_focal0 housework_t1_focal1 housework_t1_focal2 housework_t1_focal3 housework_t1_focal4 housework_t1_focal5 housework_t1_focal7 housework_t1_focal8 housework_t1_focal9 housework_t1_focal10 housework_t1_focal11 housework_t1_focal12 housework_t1_focal13 housework_t1_focal14 housework_t1_focal15  weekly_hrs_t1_focal6 weekly_hrs_t_focal6 housework_focal6 earnings_t_focal6 earnings_t1_focal6 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T1_FAMILY_6 NUM_CHILDREN_6 i.shared_birth_in_yr6_v2 i.partnered6)) housework_t1_focal6
(pmm, knn(5) include (    housework_t1_focal0 housework_t1_focal1 housework_t1_focal2 housework_t1_focal3 housework_t1_focal4 housework_t1_focal5 housework_t1_focal6 housework_t1_focal8 housework_t1_focal9 housework_t1_focal10 housework_t1_focal11 housework_t1_focal12 housework_t1_focal13 housework_t1_focal14 housework_t1_focal15   weekly_hrs_t1_focal7 weekly_hrs_t_focal7 housework_focal7 earnings_t_focal7 earnings_t1_focal7 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T1_FAMILY_7 NUM_CHILDREN_7 i.shared_birth_in_yr7_v2 i.partnered7)) housework_t1_focal7
(pmm, knn(5) include (   housework_t1_focal0 housework_t1_focal1 housework_t1_focal2 housework_t1_focal3 housework_t1_focal4 housework_t1_focal5 housework_t1_focal6 housework_t1_focal7 housework_t1_focal9 housework_t1_focal10 housework_t1_focal11 housework_t1_focal12 housework_t1_focal13 housework_t1_focal14 housework_t1_focal15    weekly_hrs_t1_focal8 weekly_hrs_t_focal8 housework_focal8 earnings_t_focal8 earnings_t1_focal8 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T1_FAMILY_8 NUM_CHILDREN_8 i.shared_birth_in_yr8_v2 i.partnered8)) housework_t1_focal8
(pmm, knn(5) include (  housework_t1_focal0 housework_t1_focal1 housework_t1_focal2 housework_t1_focal3 housework_t1_focal4 housework_t1_focal5 housework_t1_focal6 housework_t1_focal7 housework_t1_focal8 housework_t1_focal10 housework_t1_focal11 housework_t1_focal12 housework_t1_focal13 housework_t1_focal14 housework_t1_focal15     weekly_hrs_t1_focal9 weekly_hrs_t_focal9 housework_focal9 earnings_t_focal9 earnings_t1_focal9 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T1_FAMILY_9 NUM_CHILDREN_9 i.shared_birth_in_yr9_v2 i.partnered9)) housework_t1_focal9
(pmm, knn(5) include ( housework_t1_focal0 housework_t1_focal1 housework_t1_focal2 housework_t1_focal3 housework_t1_focal4 housework_t1_focal5 housework_t1_focal6 housework_t1_focal7 housework_t1_focal8 housework_t1_focal9 housework_t1_focal11 housework_t1_focal12 housework_t1_focal13 housework_t1_focal14 housework_t1_focal15      weekly_hrs_t1_focal10 weekly_hrs_t_focal10 housework_focal10 earnings_t_focal10 earnings_t1_focal10 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T1_FAMILY_10 NUM_CHILDREN_10 i.shared_birth_in_yr10_v2 i.partnered10)) housework_t1_focal10
(pmm, knn(5) include ( housework_t1_focal1 housework_t1_focal2 housework_t1_focal3 housework_t1_focal4 housework_t1_focal5 housework_t1_focal6 housework_t1_focal7 housework_t1_focal8 housework_t1_focal9 housework_t1_focal10 housework_t1_focal12 housework_t1_focal13 housework_t1_focal14 housework_t1_focal15       weekly_hrs_t1_focal11 weekly_hrs_t_focal11 housework_focal11 earnings_t_focal11 earnings_t1_focal11 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T1_FAMILY_11 NUM_CHILDREN_11 i.shared_birth_in_yr11_v2 i.partnered11)) housework_t1_focal11
(pmm, knn(5) include ( housework_t1_focal2 housework_t1_focal3 housework_t1_focal4 housework_t1_focal5 housework_t1_focal6 housework_t1_focal7 housework_t1_focal8 housework_t1_focal9 housework_t1_focal10 housework_t1_focal11 housework_t1_focal13 housework_t1_focal14 housework_t1_focal15        weekly_hrs_t1_focal12 weekly_hrs_t_focal12 housework_focal12 earnings_t_focal12 earnings_t1_focal12 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T1_FAMILY_12 NUM_CHILDREN_12 i.shared_birth_in_yr12_v2 i.partnered12)) housework_t1_focal12
(pmm, knn(5) include ( housework_t1_focal3 housework_t1_focal4 housework_t1_focal5 housework_t1_focal6 housework_t1_focal7 housework_t1_focal8 housework_t1_focal9 housework_t1_focal10 housework_t1_focal11 housework_t1_focal12 housework_t1_focal14 housework_t1_focal15         weekly_hrs_t1_focal13 weekly_hrs_t_focal13 housework_focal13 earnings_t_focal13 earnings_t1_focal13 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T1_FAMILY_13 NUM_CHILDREN_13 i.shared_birth_in_yr13_v2 i.partnered13)) housework_t1_focal13
(pmm, knn(5) include ( housework_t1_focal4 housework_t1_focal5 housework_t1_focal6 housework_t1_focal7 housework_t1_focal8 housework_t1_focal9 housework_t1_focal10 housework_t1_focal11 housework_t1_focal12 housework_t1_focal13 housework_t1_focal15          weekly_hrs_t1_focal14 weekly_hrs_t_focal14 housework_focal14 earnings_t_focal14 earnings_t1_focal14 TOTAL_INCOME_T_FAMILY14 TOTAL_INCOME_T1_FAMILY_14 NUM_CHILDREN_14 i.shared_birth_in_yr14_v2 i.partnered14)) housework_t1_focal14
(pmm, knn(5) include ( housework_t1_focal5 housework_t1_focal6 housework_t1_focal7 housework_t1_focal8 housework_t1_focal9 housework_t1_focal10 housework_t1_focal11 housework_t1_focal12 housework_t1_focal13 housework_t1_focal14           weekly_hrs_t1_focal15 weekly_hrs_t_focal15 housework_focal15 earnings_t_focal15 earnings_t1_focal15 TOTAL_INCOME_T_FAMILY15 TOTAL_INCOME_T1_FAMILY_15 NUM_CHILDREN_15 i.shared_birth_in_yr15_v2 i.partnered15)) housework_t1_focal15


/* earnings t */
(pmm, knn(5) include (           earnings_t_focal1 earnings_t_focal2 earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 weekly_hrs_t1_focal0 weekly_hrs_t_focal0 housework_t1_focal0 housework_focal0 earnings_t1_focal0 TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T1_FAMILY_0 NUM_CHILDREN_0 i.shared_birth_in_yr0_v2 i.partnered0)) earnings_t_focal0
(pmm, knn(5) include (          earnings_t_focal0 earnings_t_focal2 earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 weekly_hrs_t1_focal1 weekly_hrs_t_focal1 housework_t1_focal1 housework_focal1 earnings_t1_focal1 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T1_FAMILY_1 NUM_CHILDREN_1 i.shared_birth_in_yr1_v2 i.partnered1)) earnings_t_focal1
(pmm, knn(5) include (         earnings_t_focal0 earnings_t_focal1 earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 weekly_hrs_t1_focal2 weekly_hrs_t_focal2 housework_t1_focal2 housework_focal2 earnings_t1_focal2 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T1_FAMILY_2 NUM_CHILDREN_2 i.shared_birth_in_yr2_v2 i.partnered2)) earnings_t_focal2
(pmm, knn(5) include (        earnings_t_focal0 earnings_t_focal1 earnings_t_focal2 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 earnings_t_focal13 weekly_hrs_t1_focal3 weekly_hrs_t_focal3 housework_t1_focal3 housework_focal3 earnings_t1_focal3 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T1_FAMILY_3 NUM_CHILDREN_3 i.shared_birth_in_yr3_v2 i.partnered3)) earnings_t_focal3
(pmm, knn(5) include (       earnings_t_focal0 earnings_t_focal1 earnings_t_focal2 earnings_t_focal3 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 earnings_t_focal13 earnings_t_focal14 weekly_hrs_t1_focal4 weekly_hrs_t_focal4 housework_t1_focal4 housework_focal4 earnings_t1_focal4 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T1_FAMILY_4 NUM_CHILDREN_4 i.shared_birth_in_yr4_v2 i.partnered4)) earnings_t_focal4
(pmm, knn(5) include (      earnings_t_focal0 earnings_t_focal1 earnings_t_focal2 earnings_t_focal3 earnings_t_focal4 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 earnings_t_focal13 earnings_t_focal14 earnings_t_focal15 weekly_hrs_t1_focal5 weekly_hrs_t_focal5 housework_t1_focal5 housework_focal5 earnings_t1_focal5 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T1_FAMILY_5 NUM_CHILDREN_5 i.shared_birth_in_yr5_v2 i.partnered5)) earnings_t_focal5
(pmm, knn(5) include (     earnings_t_focal0 earnings_t_focal1 earnings_t_focal2 earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 earnings_t_focal13 earnings_t_focal14 earnings_t_focal15  weekly_hrs_t1_focal6 weekly_hrs_t_focal6 housework_t1_focal6 housework_focal6 earnings_t1_focal6 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T1_FAMILY_6 NUM_CHILDREN_6 i.shared_birth_in_yr6_v2 i.partnered6)) earnings_t_focal6
(pmm, knn(5) include (    earnings_t_focal0 earnings_t_focal1 earnings_t_focal2 earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 earnings_t_focal13 earnings_t_focal14 earnings_t_focal15   weekly_hrs_t1_focal7 weekly_hrs_t_focal7 housework_t1_focal7 housework_focal7 earnings_t1_focal7 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T1_FAMILY_7 NUM_CHILDREN_7 i.shared_birth_in_yr7_v2 i.partnered7)) earnings_t_focal7
(pmm, knn(5) include (   earnings_t_focal0 earnings_t_focal1 earnings_t_focal2 earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 earnings_t_focal13 earnings_t_focal14 earnings_t_focal15    weekly_hrs_t1_focal8 weekly_hrs_t_focal8 housework_t1_focal8 housework_focal8 earnings_t1_focal8 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T1_FAMILY_8 NUM_CHILDREN_8 i.shared_birth_in_yr8_v2 i.partnered8)) earnings_t_focal8
(pmm, knn(5) include (  earnings_t_focal0 earnings_t_focal1 earnings_t_focal2 earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 earnings_t_focal13 earnings_t_focal14 earnings_t_focal15     weekly_hrs_t1_focal9 weekly_hrs_t_focal9 housework_t1_focal9 housework_focal9 earnings_t1_focal9 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T1_FAMILY_9 NUM_CHILDREN_9 i.shared_birth_in_yr9_v2 i.partnered9)) earnings_t_focal9
(pmm, knn(5) include ( earnings_t_focal0 earnings_t_focal1 earnings_t_focal2 earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal11 earnings_t_focal12 earnings_t_focal13 earnings_t_focal14 earnings_t_focal15      weekly_hrs_t1_focal10 weekly_hrs_t_focal10 housework_t1_focal10 housework_focal10 earnings_t1_focal10 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T1_FAMILY_10 NUM_CHILDREN_10 i.shared_birth_in_yr10_v2 i.partnered10)) earnings_t_focal10
(pmm, knn(5) include ( earnings_t_focal1 earnings_t_focal2 earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal12 earnings_t_focal13 earnings_t_focal14 earnings_t_focal15       weekly_hrs_t1_focal11 weekly_hrs_t_focal11 housework_t1_focal11 housework_focal11 earnings_t1_focal11 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T1_FAMILY_11 NUM_CHILDREN_11 i.shared_birth_in_yr11_v2 i.partnered11)) earnings_t_focal11
(pmm, knn(5) include ( earnings_t_focal2 earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal13 earnings_t_focal14 earnings_t_focal15        weekly_hrs_t1_focal12 weekly_hrs_t_focal12 housework_t1_focal12 housework_focal12 earnings_t1_focal12 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T1_FAMILY_12 NUM_CHILDREN_12 i.shared_birth_in_yr12_v2 i.partnered12)) earnings_t_focal12
(pmm, knn(5) include ( earnings_t_focal3 earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 earnings_t_focal14 earnings_t_focal15         weekly_hrs_t1_focal13 weekly_hrs_t_focal13 housework_t1_focal13 housework_focal13 earnings_t1_focal13 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T1_FAMILY_13 NUM_CHILDREN_13 i.shared_birth_in_yr13_v2 i.partnered13)) earnings_t_focal13
(pmm, knn(5) include ( earnings_t_focal4 earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 earnings_t_focal13 earnings_t_focal15          weekly_hrs_t1_focal14 weekly_hrs_t_focal14 housework_t1_focal14 housework_focal14 earnings_t1_focal14 TOTAL_INCOME_T_FAMILY14 TOTAL_INCOME_T1_FAMILY_14 NUM_CHILDREN_14 i.shared_birth_in_yr14_v2 i.partnered14)) earnings_t_focal14
(pmm, knn(5) include ( earnings_t_focal5 earnings_t_focal6 earnings_t_focal7 earnings_t_focal8 earnings_t_focal9 earnings_t_focal10 earnings_t_focal11 earnings_t_focal12 earnings_t_focal13 earnings_t_focal14           weekly_hrs_t1_focal15 weekly_hrs_t_focal15 housework_t1_focal15 housework_focal15 earnings_t1_focal15 TOTAL_INCOME_T_FAMILY15 TOTAL_INCOME_T1_FAMILY_15 NUM_CHILDREN_15 i.shared_birth_in_yr15_v2 i.partnered15)) earnings_t_focal15


/* earnings t1 */
(pmm, knn(5) include (           earnings_t1_focal1 earnings_t1_focal2 earnings_t1_focal3 earnings_t1_focal4 earnings_t1_focal5 earnings_t1_focal6 earnings_t1_focal7 earnings_t1_focal8 earnings_t1_focal9 earnings_t1_focal10 weekly_hrs_t1_focal0 weekly_hrs_t_focal0 housework_t1_focal0 housework_focal0 earnings_t_focal0 TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T1_FAMILY_0 NUM_CHILDREN_0 i.shared_birth_in_yr0_v2 i.partnered0)) earnings_t1_focal0
(pmm, knn(5) include (          earnings_t1_focal0 earnings_t1_focal2 earnings_t1_focal3 earnings_t1_focal4 earnings_t1_focal5 earnings_t1_focal6 earnings_t1_focal7 earnings_t1_focal8 earnings_t1_focal9 earnings_t1_focal10 earnings_t1_focal11 weekly_hrs_t1_focal1 weekly_hrs_t_focal1 housework_t1_focal1 housework_focal1 earnings_t_focal1 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T1_FAMILY_1 NUM_CHILDREN_1 i.shared_birth_in_yr1_v2 i.partnered1)) earnings_t1_focal1
(pmm, knn(5) include (         earnings_t1_focal0 earnings_t1_focal1 earnings_t1_focal3 earnings_t1_focal4 earnings_t1_focal5 earnings_t1_focal6 earnings_t1_focal7 earnings_t1_focal8 earnings_t1_focal9 earnings_t1_focal10 earnings_t1_focal11 earnings_t1_focal12 weekly_hrs_t1_focal2 weekly_hrs_t_focal2 housework_t1_focal2 housework_focal2 earnings_t_focal2 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T1_FAMILY_2 NUM_CHILDREN_2 i.shared_birth_in_yr2_v2 i.partnered2)) earnings_t1_focal2
(pmm, knn(5) include (        earnings_t1_focal0 earnings_t1_focal1 earnings_t1_focal2 earnings_t1_focal4 earnings_t1_focal5 earnings_t1_focal6 earnings_t1_focal7 earnings_t1_focal8 earnings_t1_focal9 earnings_t1_focal10 earnings_t1_focal11 earnings_t1_focal12 earnings_t1_focal13 weekly_hrs_t1_focal3 weekly_hrs_t_focal3 housework_t1_focal3 housework_focal3 earnings_t_focal3 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T1_FAMILY_3 NUM_CHILDREN_3 i.shared_birth_in_yr3_v2 i.partnered3)) earnings_t1_focal3
(pmm, knn(5) include (       earnings_t1_focal0 earnings_t1_focal1 earnings_t1_focal2 earnings_t1_focal3 earnings_t1_focal5 earnings_t1_focal6 earnings_t1_focal7 earnings_t1_focal8 earnings_t1_focal9 earnings_t1_focal10 earnings_t1_focal11 earnings_t1_focal12 earnings_t1_focal13 earnings_t1_focal14 weekly_hrs_t1_focal4 weekly_hrs_t_focal4 housework_t1_focal4 housework_focal4 earnings_t_focal4 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T1_FAMILY_4 NUM_CHILDREN_4 i.shared_birth_in_yr4_v2 i.partnered4)) earnings_t1_focal4
(pmm, knn(5) include (      earnings_t1_focal0 earnings_t1_focal1 earnings_t1_focal2 earnings_t1_focal3 earnings_t1_focal4 earnings_t1_focal6 earnings_t1_focal7 earnings_t1_focal8 earnings_t1_focal9 earnings_t1_focal10 earnings_t1_focal11 earnings_t1_focal12 earnings_t1_focal13 earnings_t1_focal14 earnings_t1_focal15 weekly_hrs_t1_focal5 weekly_hrs_t_focal5 housework_t1_focal5 housework_focal5 earnings_t_focal5 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T1_FAMILY_5 NUM_CHILDREN_5 i.shared_birth_in_yr5_v2 i.partnered5)) earnings_t1_focal5
(pmm, knn(5) include (     earnings_t1_focal0 earnings_t1_focal1 earnings_t1_focal2 earnings_t1_focal3 earnings_t1_focal4 earnings_t1_focal5 earnings_t1_focal7 earnings_t1_focal8 earnings_t1_focal9 earnings_t1_focal10 earnings_t1_focal11 earnings_t1_focal12 earnings_t1_focal13 earnings_t1_focal14 earnings_t1_focal15  weekly_hrs_t1_focal6 weekly_hrs_t_focal6 housework_t1_focal6 housework_focal6 earnings_t_focal6 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T1_FAMILY_6 NUM_CHILDREN_6 i.shared_birth_in_yr6_v2 i.partnered6)) earnings_t1_focal6
(pmm, knn(5) include (    earnings_t1_focal0 earnings_t1_focal1 earnings_t1_focal2 earnings_t1_focal3 earnings_t1_focal4 earnings_t1_focal5 earnings_t1_focal6 earnings_t1_focal8 earnings_t1_focal9 earnings_t1_focal10 earnings_t1_focal11 earnings_t1_focal12 earnings_t1_focal13 earnings_t1_focal14 earnings_t1_focal15   weekly_hrs_t1_focal7 weekly_hrs_t_focal7 housework_t1_focal7 housework_focal7 earnings_t_focal7 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T1_FAMILY_7 NUM_CHILDREN_7 i.shared_birth_in_yr7_v2 i.partnered7)) earnings_t1_focal7
(pmm, knn(5) include (   earnings_t1_focal0 earnings_t1_focal1 earnings_t1_focal2 earnings_t1_focal3 earnings_t1_focal4 earnings_t1_focal5 earnings_t1_focal6 earnings_t1_focal7 earnings_t1_focal9 earnings_t1_focal10 earnings_t1_focal11 earnings_t1_focal12 earnings_t1_focal13 earnings_t1_focal14 earnings_t1_focal15    weekly_hrs_t1_focal8 weekly_hrs_t_focal8 housework_t1_focal8 housework_focal8 earnings_t_focal8 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T1_FAMILY_8 NUM_CHILDREN_8 i.shared_birth_in_yr8_v2 i.partnered8)) earnings_t1_focal8
(pmm, knn(5) include (  earnings_t1_focal0 earnings_t1_focal1 earnings_t1_focal2 earnings_t1_focal3 earnings_t1_focal4 earnings_t1_focal5 earnings_t1_focal6 earnings_t1_focal7 earnings_t1_focal8 earnings_t1_focal10 earnings_t1_focal11 earnings_t1_focal12 earnings_t1_focal13 earnings_t1_focal14 earnings_t1_focal15     weekly_hrs_t1_focal9 weekly_hrs_t_focal9 housework_t1_focal9 housework_focal9 earnings_t_focal9 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T1_FAMILY_9 NUM_CHILDREN_9 i.shared_birth_in_yr9_v2 i.partnered9)) earnings_t1_focal9
(pmm, knn(5) include ( earnings_t1_focal0 earnings_t1_focal1 earnings_t1_focal2 earnings_t1_focal3 earnings_t1_focal4 earnings_t1_focal5 earnings_t1_focal6 earnings_t1_focal7 earnings_t1_focal8 earnings_t1_focal9 earnings_t1_focal11 earnings_t1_focal12 earnings_t1_focal13 earnings_t1_focal14 earnings_t1_focal15      weekly_hrs_t1_focal10 weekly_hrs_t_focal10 housework_t1_focal10 housework_focal10 earnings_t_focal10 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T1_FAMILY_10 NUM_CHILDREN_10 i.shared_birth_in_yr10_v2 i.partnered10)) earnings_t1_focal10
(pmm, knn(5) include ( earnings_t1_focal1 earnings_t1_focal2 earnings_t1_focal3 earnings_t1_focal4 earnings_t1_focal5 earnings_t1_focal6 earnings_t1_focal7 earnings_t1_focal8 earnings_t1_focal9 earnings_t1_focal10 earnings_t1_focal12 earnings_t1_focal13 earnings_t1_focal14 earnings_t1_focal15       weekly_hrs_t1_focal11 weekly_hrs_t_focal11 housework_t1_focal11 housework_focal11 earnings_t_focal11 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T1_FAMILY_11 NUM_CHILDREN_11 i.shared_birth_in_yr11_v2 i.partnered11)) earnings_t1_focal11
(pmm, knn(5) include ( earnings_t1_focal2 earnings_t1_focal3 earnings_t1_focal4 earnings_t1_focal5 earnings_t1_focal6 earnings_t1_focal7 earnings_t1_focal8 earnings_t1_focal9 earnings_t1_focal10 earnings_t1_focal11 earnings_t1_focal13 earnings_t1_focal14 earnings_t1_focal15        weekly_hrs_t1_focal12 weekly_hrs_t_focal12 housework_t1_focal12 housework_focal12 earnings_t_focal12 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T1_FAMILY_12 NUM_CHILDREN_12 i.shared_birth_in_yr12_v2 i.partnered12)) earnings_t1_focal12
(pmm, knn(5) include ( earnings_t1_focal3 earnings_t1_focal4 earnings_t1_focal5 earnings_t1_focal6 earnings_t1_focal7 earnings_t1_focal8 earnings_t1_focal9 earnings_t1_focal10 earnings_t1_focal11 earnings_t1_focal12 earnings_t1_focal14 earnings_t1_focal15         weekly_hrs_t1_focal13 weekly_hrs_t_focal13 housework_t1_focal13 housework_focal13 earnings_t_focal13 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T1_FAMILY_13 NUM_CHILDREN_13 i.shared_birth_in_yr13_v2 i.partnered13)) earnings_t1_focal13
(pmm, knn(5) include ( earnings_t1_focal4 earnings_t1_focal5 earnings_t1_focal6 earnings_t1_focal7 earnings_t1_focal8 earnings_t1_focal9 earnings_t1_focal10 earnings_t1_focal11 earnings_t1_focal12 earnings_t1_focal13 earnings_t1_focal15          weekly_hrs_t1_focal14 weekly_hrs_t_focal14 housework_t1_focal14 housework_focal14 earnings_t_focal14 TOTAL_INCOME_T_FAMILY14 TOTAL_INCOME_T1_FAMILY_14 NUM_CHILDREN_14 i.shared_birth_in_yr14_v2 i.partnered14)) earnings_t1_focal14
(pmm, knn(5) include ( earnings_t1_focal5 earnings_t1_focal6 earnings_t1_focal7 earnings_t1_focal8 earnings_t1_focal9 earnings_t1_focal10 earnings_t1_focal11 earnings_t1_focal12 earnings_t1_focal13 earnings_t1_focal14           weekly_hrs_t1_focal15 weekly_hrs_t_focal15 housework_t1_focal15 housework_focal15 earnings_t_focal15 TOTAL_INCOME_T_FAMILY15 TOTAL_INCOME_T1_FAMILY_15 NUM_CHILDREN_15 i.shared_birth_in_yr15_v2 i.partnered15)) earnings_t1_focal15

/* family income t */
(pmm, knn(5) include (           TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 weekly_hrs_t1_focal0 weekly_hrs_t_focal0 housework_t1_focal0 housework_focal0 earnings_t1_focal0 earnings_t_focal0 TOTAL_INCOME_T1_FAMILY_0 NUM_CHILDREN_0 i.shared_birth_in_yr0_v2 i.partnered0)) TOTAL_INCOME_T_FAMILY0
(pmm, knn(5) include (          TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 weekly_hrs_t1_focal1 weekly_hrs_t_focal1 housework_t1_focal1 housework_focal1 earnings_t1_focal1 earnings_t_focal1 TOTAL_INCOME_T1_FAMILY_1 NUM_CHILDREN_1 i.shared_birth_in_yr1_v2 i.partnered1)) TOTAL_INCOME_T_FAMILY1
(pmm, knn(5) include (         TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 weekly_hrs_t1_focal2 weekly_hrs_t_focal2 housework_t1_focal2 housework_focal2 earnings_t1_focal2 earnings_t_focal2 TOTAL_INCOME_T1_FAMILY_2 NUM_CHILDREN_2 i.shared_birth_in_yr2_v2 i.partnered2)) TOTAL_INCOME_T_FAMILY2
(pmm, knn(5) include (        TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 weekly_hrs_t1_focal3 weekly_hrs_t_focal3 housework_t1_focal3 housework_focal3 earnings_t1_focal3 earnings_t_focal3 TOTAL_INCOME_T1_FAMILY_3 NUM_CHILDREN_3 i.shared_birth_in_yr3_v2 i.partnered3)) TOTAL_INCOME_T_FAMILY3
(pmm, knn(5) include (       TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14 weekly_hrs_t1_focal4 weekly_hrs_t_focal4 housework_t1_focal4 housework_focal4 earnings_t1_focal4 earnings_t_focal4 TOTAL_INCOME_T1_FAMILY_4 NUM_CHILDREN_4 i.shared_birth_in_yr4_v2 i.partnered4)) TOTAL_INCOME_T_FAMILY4
(pmm, knn(5) include (      TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14 TOTAL_INCOME_T_FAMILY15 weekly_hrs_t1_focal5 weekly_hrs_t_focal5 housework_t1_focal5 housework_focal5 earnings_t1_focal5 earnings_t_focal5 TOTAL_INCOME_T1_FAMILY_5 NUM_CHILDREN_5 i.shared_birth_in_yr5_v2 i.partnered5)) TOTAL_INCOME_T_FAMILY5
(pmm, knn(5) include (     TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14 TOTAL_INCOME_T_FAMILY15  weekly_hrs_t1_focal6 weekly_hrs_t_focal6 housework_t1_focal6 housework_focal6 earnings_t1_focal6 earnings_t_focal6 TOTAL_INCOME_T1_FAMILY_6 NUM_CHILDREN_6 i.shared_birth_in_yr6_v2 i.partnered6)) TOTAL_INCOME_T_FAMILY6
(pmm, knn(5) include (    TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14 TOTAL_INCOME_T_FAMILY15   weekly_hrs_t1_focal7 weekly_hrs_t_focal7 housework_t1_focal7 housework_focal7 earnings_t1_focal7 earnings_t_focal7 TOTAL_INCOME_T1_FAMILY_7 NUM_CHILDREN_7 i.shared_birth_in_yr7_v2 i.partnered7)) TOTAL_INCOME_T_FAMILY7
(pmm, knn(5) include (   TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14 TOTAL_INCOME_T_FAMILY15    weekly_hrs_t1_focal8 weekly_hrs_t_focal8 housework_t1_focal8 housework_focal8 earnings_t1_focal8 earnings_t_focal8 TOTAL_INCOME_T1_FAMILY_8 NUM_CHILDREN_8 i.shared_birth_in_yr8_v2 i.partnered8)) TOTAL_INCOME_T_FAMILY8
(pmm, knn(5) include (  TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14 TOTAL_INCOME_T_FAMILY15     weekly_hrs_t1_focal9 weekly_hrs_t_focal9 housework_t1_focal9 housework_focal9 earnings_t1_focal9 earnings_t_focal9 TOTAL_INCOME_T1_FAMILY_9 NUM_CHILDREN_9 i.shared_birth_in_yr9_v2 i.partnered9)) TOTAL_INCOME_T_FAMILY9
(pmm, knn(5) include ( TOTAL_INCOME_T_FAMILY0 TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14 TOTAL_INCOME_T_FAMILY15      weekly_hrs_t1_focal10 weekly_hrs_t_focal10 housework_t1_focal10 housework_focal10 earnings_t1_focal10 earnings_t_focal10 TOTAL_INCOME_T1_FAMILY_10 NUM_CHILDREN_10 i.shared_birth_in_yr10_v2 i.partnered10)) TOTAL_INCOME_T_FAMILY10
(pmm, knn(5) include ( TOTAL_INCOME_T_FAMILY1 TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14 TOTAL_INCOME_T_FAMILY15       weekly_hrs_t1_focal11 weekly_hrs_t_focal11 housework_t1_focal11 housework_focal11 earnings_t1_focal11 earnings_t_focal11 TOTAL_INCOME_T1_FAMILY_11 NUM_CHILDREN_11 i.shared_birth_in_yr11_v2 i.partnered11)) TOTAL_INCOME_T_FAMILY11
(pmm, knn(5) include ( TOTAL_INCOME_T_FAMILY2 TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14 TOTAL_INCOME_T_FAMILY15        weekly_hrs_t1_focal12 weekly_hrs_t_focal12 housework_t1_focal12 housework_focal12 earnings_t1_focal12 earnings_t_focal12 TOTAL_INCOME_T1_FAMILY_12 NUM_CHILDREN_12 i.shared_birth_in_yr12_v2 i.partnered12)) TOTAL_INCOME_T_FAMILY12
(pmm, knn(5) include ( TOTAL_INCOME_T_FAMILY3 TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY14 TOTAL_INCOME_T_FAMILY15         weekly_hrs_t1_focal13 weekly_hrs_t_focal13 housework_t1_focal13 housework_focal13 earnings_t1_focal13 earnings_t_focal13 TOTAL_INCOME_T1_FAMILY_13 NUM_CHILDREN_13 i.shared_birth_in_yr13_v2 i.partnered13)) TOTAL_INCOME_T_FAMILY13
(pmm, knn(5) include ( TOTAL_INCOME_T_FAMILY4 TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY15          weekly_hrs_t1_focal14 weekly_hrs_t_focal14 housework_t1_focal14 housework_focal14 earnings_t1_focal14 earnings_t_focal14 TOTAL_INCOME_T1_FAMILY_14 NUM_CHILDREN_14 i.shared_birth_in_yr14_v2 i.partnered14)) TOTAL_INCOME_T_FAMILY14
(pmm, knn(5) include ( TOTAL_INCOME_T_FAMILY5 TOTAL_INCOME_T_FAMILY6 TOTAL_INCOME_T_FAMILY7 TOTAL_INCOME_T_FAMILY8 TOTAL_INCOME_T_FAMILY9 TOTAL_INCOME_T_FAMILY10 TOTAL_INCOME_T_FAMILY11 TOTAL_INCOME_T_FAMILY12 TOTAL_INCOME_T_FAMILY13 TOTAL_INCOME_T_FAMILY14           weekly_hrs_t1_focal15 weekly_hrs_t_focal15 housework_t1_focal15 housework_focal15 earnings_t1_focal15 earnings_t_focal15 TOTAL_INCOME_T1_FAMILY_15 NUM_CHILDREN_15 i.shared_birth_in_yr15_v2 i.partnered15)) TOTAL_INCOME_T_FAMILY15


/* family income t1 */
(pmm, knn(5) include (           TOTAL_INCOME_T1_FAMILY_1 TOTAL_INCOME_T1_FAMILY_2 TOTAL_INCOME_T1_FAMILY_3 TOTAL_INCOME_T1_FAMILY_4 TOTAL_INCOME_T1_FAMILY_5 TOTAL_INCOME_T1_FAMILY_6 TOTAL_INCOME_T1_FAMILY_7 TOTAL_INCOME_T1_FAMILY_8 TOTAL_INCOME_T1_FAMILY_9 TOTAL_INCOME_T1_FAMILY_10 weekly_hrs_t1_focal0 weekly_hrs_t_focal0 housework_t1_focal0 housework_focal0 earnings_t1_focal0 earnings_t_focal0 TOTAL_INCOME_T_FAMILY0 NUM_CHILDREN_0 i.shared_birth_in_yr0_v2 i.partnered0)) TOTAL_INCOME_T1_FAMILY_0
(pmm, knn(5) include (          TOTAL_INCOME_T1_FAMILY_0 TOTAL_INCOME_T1_FAMILY_2 TOTAL_INCOME_T1_FAMILY_3 TOTAL_INCOME_T1_FAMILY_4 TOTAL_INCOME_T1_FAMILY_5 TOTAL_INCOME_T1_FAMILY_6 TOTAL_INCOME_T1_FAMILY_7 TOTAL_INCOME_T1_FAMILY_8 TOTAL_INCOME_T1_FAMILY_9 TOTAL_INCOME_T1_FAMILY_10 TOTAL_INCOME_T1_FAMILY_11 weekly_hrs_t1_focal1 weekly_hrs_t_focal1 housework_t1_focal1 housework_focal1 earnings_t1_focal1 earnings_t_focal1 TOTAL_INCOME_T_FAMILY1 NUM_CHILDREN_1 i.shared_birth_in_yr1_v2 i.partnered1)) TOTAL_INCOME_T1_FAMILY_1
(pmm, knn(5) include (         TOTAL_INCOME_T1_FAMILY_0 TOTAL_INCOME_T1_FAMILY_1 TOTAL_INCOME_T1_FAMILY_3 TOTAL_INCOME_T1_FAMILY_4 TOTAL_INCOME_T1_FAMILY_5 TOTAL_INCOME_T1_FAMILY_6 TOTAL_INCOME_T1_FAMILY_7 TOTAL_INCOME_T1_FAMILY_8 TOTAL_INCOME_T1_FAMILY_9 TOTAL_INCOME_T1_FAMILY_10 TOTAL_INCOME_T1_FAMILY_11 TOTAL_INCOME_T1_FAMILY_12 weekly_hrs_t1_focal2 weekly_hrs_t_focal2 housework_t1_focal2 housework_focal2 earnings_t1_focal2 earnings_t_focal2 TOTAL_INCOME_T_FAMILY2 NUM_CHILDREN_2 i.shared_birth_in_yr2_v2 i.partnered2)) TOTAL_INCOME_T1_FAMILY_2
(pmm, knn(5) include (        TOTAL_INCOME_T1_FAMILY_0 TOTAL_INCOME_T1_FAMILY_1 TOTAL_INCOME_T1_FAMILY_2 TOTAL_INCOME_T1_FAMILY_4 TOTAL_INCOME_T1_FAMILY_5 TOTAL_INCOME_T1_FAMILY_6 TOTAL_INCOME_T1_FAMILY_7 TOTAL_INCOME_T1_FAMILY_8 TOTAL_INCOME_T1_FAMILY_9 TOTAL_INCOME_T1_FAMILY_10 TOTAL_INCOME_T1_FAMILY_11 TOTAL_INCOME_T1_FAMILY_12 TOTAL_INCOME_T1_FAMILY_13 weekly_hrs_t1_focal3 weekly_hrs_t_focal3 housework_t1_focal3 housework_focal3 earnings_t1_focal3 earnings_t_focal3 TOTAL_INCOME_T_FAMILY3 NUM_CHILDREN_3 i.shared_birth_in_yr3_v2 i.partnered3)) TOTAL_INCOME_T1_FAMILY_3
(pmm, knn(5) include (       TOTAL_INCOME_T1_FAMILY_0 TOTAL_INCOME_T1_FAMILY_1 TOTAL_INCOME_T1_FAMILY_2 TOTAL_INCOME_T1_FAMILY_3 TOTAL_INCOME_T1_FAMILY_5 TOTAL_INCOME_T1_FAMILY_6 TOTAL_INCOME_T1_FAMILY_7 TOTAL_INCOME_T1_FAMILY_8 TOTAL_INCOME_T1_FAMILY_9 TOTAL_INCOME_T1_FAMILY_10 TOTAL_INCOME_T1_FAMILY_11 TOTAL_INCOME_T1_FAMILY_12 TOTAL_INCOME_T1_FAMILY_13 TOTAL_INCOME_T1_FAMILY_14 weekly_hrs_t1_focal4 weekly_hrs_t_focal4 housework_t1_focal4 housework_focal4 earnings_t1_focal4 earnings_t_focal4 TOTAL_INCOME_T_FAMILY4 NUM_CHILDREN_4 i.shared_birth_in_yr4_v2 i.partnered4)) TOTAL_INCOME_T1_FAMILY_4
(pmm, knn(5) include (      TOTAL_INCOME_T1_FAMILY_0 TOTAL_INCOME_T1_FAMILY_1 TOTAL_INCOME_T1_FAMILY_2 TOTAL_INCOME_T1_FAMILY_3 TOTAL_INCOME_T1_FAMILY_4 TOTAL_INCOME_T1_FAMILY_6 TOTAL_INCOME_T1_FAMILY_7 TOTAL_INCOME_T1_FAMILY_8 TOTAL_INCOME_T1_FAMILY_9 TOTAL_INCOME_T1_FAMILY_10 TOTAL_INCOME_T1_FAMILY_11 TOTAL_INCOME_T1_FAMILY_12 TOTAL_INCOME_T1_FAMILY_13 TOTAL_INCOME_T1_FAMILY_14 TOTAL_INCOME_T1_FAMILY_15 weekly_hrs_t1_focal5 weekly_hrs_t_focal5 housework_t1_focal5 housework_focal5 earnings_t1_focal5 earnings_t_focal5 TOTAL_INCOME_T_FAMILY5 NUM_CHILDREN_5 i.shared_birth_in_yr5_v2 i.partnered5)) TOTAL_INCOME_T1_FAMILY_5
(pmm, knn(5) include (     TOTAL_INCOME_T1_FAMILY_0 TOTAL_INCOME_T1_FAMILY_1 TOTAL_INCOME_T1_FAMILY_2 TOTAL_INCOME_T1_FAMILY_3 TOTAL_INCOME_T1_FAMILY_4 TOTAL_INCOME_T1_FAMILY_5 TOTAL_INCOME_T1_FAMILY_7 TOTAL_INCOME_T1_FAMILY_8 TOTAL_INCOME_T1_FAMILY_9 TOTAL_INCOME_T1_FAMILY_10 TOTAL_INCOME_T1_FAMILY_11 TOTAL_INCOME_T1_FAMILY_12 TOTAL_INCOME_T1_FAMILY_13 TOTAL_INCOME_T1_FAMILY_14 TOTAL_INCOME_T1_FAMILY_15  weekly_hrs_t1_focal6 weekly_hrs_t_focal6 housework_t1_focal6 housework_focal6 earnings_t1_focal6 earnings_t_focal6 TOTAL_INCOME_T_FAMILY6 NUM_CHILDREN_6 i.shared_birth_in_yr6_v2 i.partnered6)) TOTAL_INCOME_T1_FAMILY_6
(pmm, knn(5) include (    TOTAL_INCOME_T1_FAMILY_0 TOTAL_INCOME_T1_FAMILY_1 TOTAL_INCOME_T1_FAMILY_2 TOTAL_INCOME_T1_FAMILY_3 TOTAL_INCOME_T1_FAMILY_4 TOTAL_INCOME_T1_FAMILY_5 TOTAL_INCOME_T1_FAMILY_6 TOTAL_INCOME_T1_FAMILY_8 TOTAL_INCOME_T1_FAMILY_9 TOTAL_INCOME_T1_FAMILY_10 TOTAL_INCOME_T1_FAMILY_11 TOTAL_INCOME_T1_FAMILY_12 TOTAL_INCOME_T1_FAMILY_13 TOTAL_INCOME_T1_FAMILY_14 TOTAL_INCOME_T1_FAMILY_15   weekly_hrs_t1_focal7 weekly_hrs_t_focal7 housework_t1_focal7 housework_focal7 earnings_t1_focal7 earnings_t_focal7 TOTAL_INCOME_T_FAMILY7 NUM_CHILDREN_7 i.shared_birth_in_yr7_v2 i.partnered7)) TOTAL_INCOME_T1_FAMILY_7
(pmm, knn(5) include (   TOTAL_INCOME_T1_FAMILY_0 TOTAL_INCOME_T1_FAMILY_1 TOTAL_INCOME_T1_FAMILY_2 TOTAL_INCOME_T1_FAMILY_3 TOTAL_INCOME_T1_FAMILY_4 TOTAL_INCOME_T1_FAMILY_5 TOTAL_INCOME_T1_FAMILY_6 TOTAL_INCOME_T1_FAMILY_7 TOTAL_INCOME_T1_FAMILY_9 TOTAL_INCOME_T1_FAMILY_10 TOTAL_INCOME_T1_FAMILY_11 TOTAL_INCOME_T1_FAMILY_12 TOTAL_INCOME_T1_FAMILY_13 TOTAL_INCOME_T1_FAMILY_14 TOTAL_INCOME_T1_FAMILY_15    weekly_hrs_t1_focal8 weekly_hrs_t_focal8 housework_t1_focal8 housework_focal8 earnings_t1_focal8 earnings_t_focal8 TOTAL_INCOME_T_FAMILY8 NUM_CHILDREN_8 i.shared_birth_in_yr8_v2 i.partnered8)) TOTAL_INCOME_T1_FAMILY_8
(pmm, knn(5) include (  TOTAL_INCOME_T1_FAMILY_0 TOTAL_INCOME_T1_FAMILY_1 TOTAL_INCOME_T1_FAMILY_2 TOTAL_INCOME_T1_FAMILY_3 TOTAL_INCOME_T1_FAMILY_4 TOTAL_INCOME_T1_FAMILY_5 TOTAL_INCOME_T1_FAMILY_6 TOTAL_INCOME_T1_FAMILY_7 TOTAL_INCOME_T1_FAMILY_8 TOTAL_INCOME_T1_FAMILY_10 TOTAL_INCOME_T1_FAMILY_11 TOTAL_INCOME_T1_FAMILY_12 TOTAL_INCOME_T1_FAMILY_13 TOTAL_INCOME_T1_FAMILY_14 TOTAL_INCOME_T1_FAMILY_15     weekly_hrs_t1_focal9 weekly_hrs_t_focal9 housework_t1_focal9 housework_focal9 earnings_t1_focal9 earnings_t_focal9 TOTAL_INCOME_T_FAMILY9 NUM_CHILDREN_9 i.shared_birth_in_yr9_v2 i.partnered9)) TOTAL_INCOME_T1_FAMILY_9
(pmm, knn(5) include ( TOTAL_INCOME_T1_FAMILY_0 TOTAL_INCOME_T1_FAMILY_1 TOTAL_INCOME_T1_FAMILY_2 TOTAL_INCOME_T1_FAMILY_3 TOTAL_INCOME_T1_FAMILY_4 TOTAL_INCOME_T1_FAMILY_5 TOTAL_INCOME_T1_FAMILY_6 TOTAL_INCOME_T1_FAMILY_7 TOTAL_INCOME_T1_FAMILY_8 TOTAL_INCOME_T1_FAMILY_9 TOTAL_INCOME_T1_FAMILY_11 TOTAL_INCOME_T1_FAMILY_12 TOTAL_INCOME_T1_FAMILY_13 TOTAL_INCOME_T1_FAMILY_14 TOTAL_INCOME_T1_FAMILY_15      weekly_hrs_t1_focal10 weekly_hrs_t_focal10 housework_t1_focal10 housework_focal10 earnings_t1_focal10 earnings_t_focal10 TOTAL_INCOME_T_FAMILY10 NUM_CHILDREN_10 i.shared_birth_in_yr10_v2 i.partnered10)) TOTAL_INCOME_T1_FAMILY_10
(pmm, knn(5) include ( TOTAL_INCOME_T1_FAMILY_1 TOTAL_INCOME_T1_FAMILY_2 TOTAL_INCOME_T1_FAMILY_3 TOTAL_INCOME_T1_FAMILY_4 TOTAL_INCOME_T1_FAMILY_5 TOTAL_INCOME_T1_FAMILY_6 TOTAL_INCOME_T1_FAMILY_7 TOTAL_INCOME_T1_FAMILY_8 TOTAL_INCOME_T1_FAMILY_9 TOTAL_INCOME_T1_FAMILY_10 TOTAL_INCOME_T1_FAMILY_12 TOTAL_INCOME_T1_FAMILY_13 TOTAL_INCOME_T1_FAMILY_14 TOTAL_INCOME_T1_FAMILY_15       weekly_hrs_t1_focal11 weekly_hrs_t_focal11 housework_t1_focal11 housework_focal11 earnings_t1_focal11 earnings_t_focal11 TOTAL_INCOME_T_FAMILY11 NUM_CHILDREN_11 i.shared_birth_in_yr11_v2 i.partnered11)) TOTAL_INCOME_T1_FAMILY_11
(pmm, knn(5) include ( TOTAL_INCOME_T1_FAMILY_2 TOTAL_INCOME_T1_FAMILY_3 TOTAL_INCOME_T1_FAMILY_4 TOTAL_INCOME_T1_FAMILY_5 TOTAL_INCOME_T1_FAMILY_6 TOTAL_INCOME_T1_FAMILY_7 TOTAL_INCOME_T1_FAMILY_8 TOTAL_INCOME_T1_FAMILY_9 TOTAL_INCOME_T1_FAMILY_10 TOTAL_INCOME_T1_FAMILY_11 TOTAL_INCOME_T1_FAMILY_13 TOTAL_INCOME_T1_FAMILY_14 TOTAL_INCOME_T1_FAMILY_15        weekly_hrs_t1_focal12 weekly_hrs_t_focal12 housework_t1_focal12 housework_focal12 earnings_t1_focal12 earnings_t_focal12 TOTAL_INCOME_T_FAMILY12 NUM_CHILDREN_12 i.shared_birth_in_yr12_v2 i.partnered12)) TOTAL_INCOME_T1_FAMILY_12
(pmm, knn(5) include ( TOTAL_INCOME_T1_FAMILY_3 TOTAL_INCOME_T1_FAMILY_4 TOTAL_INCOME_T1_FAMILY_5 TOTAL_INCOME_T1_FAMILY_6 TOTAL_INCOME_T1_FAMILY_7 TOTAL_INCOME_T1_FAMILY_8 TOTAL_INCOME_T1_FAMILY_9 TOTAL_INCOME_T1_FAMILY_10 TOTAL_INCOME_T1_FAMILY_11 TOTAL_INCOME_T1_FAMILY_12 TOTAL_INCOME_T1_FAMILY_14 TOTAL_INCOME_T1_FAMILY_15         weekly_hrs_t1_focal13 weekly_hrs_t_focal13 housework_t1_focal13 housework_focal13 earnings_t1_focal13 earnings_t_focal13 TOTAL_INCOME_T_FAMILY13 NUM_CHILDREN_13 i.shared_birth_in_yr13_v2 i.partnered13)) TOTAL_INCOME_T1_FAMILY_13
(pmm, knn(5) include ( TOTAL_INCOME_T1_FAMILY_4 TOTAL_INCOME_T1_FAMILY_5 TOTAL_INCOME_T1_FAMILY_6 TOTAL_INCOME_T1_FAMILY_7 TOTAL_INCOME_T1_FAMILY_8 TOTAL_INCOME_T1_FAMILY_9 TOTAL_INCOME_T1_FAMILY_10 TOTAL_INCOME_T1_FAMILY_11 TOTAL_INCOME_T1_FAMILY_12 TOTAL_INCOME_T1_FAMILY_13 TOTAL_INCOME_T1_FAMILY_15          weekly_hrs_t1_focal14 weekly_hrs_t_focal14 housework_t1_focal14 housework_focal14 earnings_t1_focal14 earnings_t_focal14 TOTAL_INCOME_T_FAMILY14 NUM_CHILDREN_14 i.shared_birth_in_yr14_v2 i.partnered14)) TOTAL_INCOME_T1_FAMILY_14
(pmm, knn(5) include ( TOTAL_INCOME_T1_FAMILY_5 TOTAL_INCOME_T1_FAMILY_6 TOTAL_INCOME_T1_FAMILY_7 TOTAL_INCOME_T1_FAMILY_8 TOTAL_INCOME_T1_FAMILY_9 TOTAL_INCOME_T1_FAMILY_10 TOTAL_INCOME_T1_FAMILY_11 TOTAL_INCOME_T1_FAMILY_12 TOTAL_INCOME_T1_FAMILY_13 TOTAL_INCOME_T1_FAMILY_14           weekly_hrs_t1_focal15 weekly_hrs_t_focal15 housework_t1_focal15 housework_focal15 earnings_t1_focal15 earnings_t_focal15 TOTAL_INCOME_T_FAMILY15 NUM_CHILDREN_15 i.shared_birth_in_yr15_v2 i.partnered15)) TOTAL_INCOME_T1_FAMILY_15


/* number of children */
(pmm, knn(5) include (           NUM_CHILDREN_1 NUM_CHILDREN_2 NUM_CHILDREN_3 NUM_CHILDREN_4 NUM_CHILDREN_5 NUM_CHILDREN_6 NUM_CHILDREN_7 NUM_CHILDREN_8 NUM_CHILDREN_9 NUM_CHILDREN_10 weekly_hrs_t1_focal0 weekly_hrs_t_focal0 housework_t1_focal0 housework_focal0 earnings_t1_focal0 earnings_t_focal0 TOTAL_INCOME_T1_FAMILY_0 TOTAL_INCOME_T_FAMILY0 i.shared_birth_in_yr0_v2 i.partnered0)) NUM_CHILDREN_0
(pmm, knn(5) include (          NUM_CHILDREN_0 NUM_CHILDREN_2 NUM_CHILDREN_3 NUM_CHILDREN_4 NUM_CHILDREN_5 NUM_CHILDREN_6 NUM_CHILDREN_7 NUM_CHILDREN_8 NUM_CHILDREN_9 NUM_CHILDREN_10 NUM_CHILDREN_11 weekly_hrs_t1_focal1 weekly_hrs_t_focal1 housework_t1_focal1 housework_focal1 earnings_t1_focal1 earnings_t_focal1 TOTAL_INCOME_T1_FAMILY_1 TOTAL_INCOME_T_FAMILY1 i.shared_birth_in_yr1_v2 i.partnered1)) NUM_CHILDREN_1
(pmm, knn(5) include (         NUM_CHILDREN_0 NUM_CHILDREN_1 NUM_CHILDREN_3 NUM_CHILDREN_4 NUM_CHILDREN_5 NUM_CHILDREN_6 NUM_CHILDREN_7 NUM_CHILDREN_8 NUM_CHILDREN_9 NUM_CHILDREN_10 NUM_CHILDREN_11 NUM_CHILDREN_12 weekly_hrs_t1_focal2 weekly_hrs_t_focal2 housework_t1_focal2 housework_focal2 earnings_t1_focal2 earnings_t_focal2 TOTAL_INCOME_T1_FAMILY_2 TOTAL_INCOME_T_FAMILY2 i.shared_birth_in_yr2_v2 i.partnered2)) NUM_CHILDREN_2
(pmm, knn(5) include (        NUM_CHILDREN_0 NUM_CHILDREN_1 NUM_CHILDREN_2 NUM_CHILDREN_4 NUM_CHILDREN_5 NUM_CHILDREN_6 NUM_CHILDREN_7 NUM_CHILDREN_8 NUM_CHILDREN_9 NUM_CHILDREN_10 NUM_CHILDREN_11 NUM_CHILDREN_12 NUM_CHILDREN_13 weekly_hrs_t1_focal3 weekly_hrs_t_focal3 housework_t1_focal3 housework_focal3 earnings_t1_focal3 earnings_t_focal3 TOTAL_INCOME_T1_FAMILY_3 TOTAL_INCOME_T_FAMILY3 i.shared_birth_in_yr3_v2 i.partnered3)) NUM_CHILDREN_3
(pmm, knn(5) include (       NUM_CHILDREN_0 NUM_CHILDREN_1 NUM_CHILDREN_2 NUM_CHILDREN_3 NUM_CHILDREN_5 NUM_CHILDREN_6 NUM_CHILDREN_7 NUM_CHILDREN_8 NUM_CHILDREN_9 NUM_CHILDREN_10 NUM_CHILDREN_11 NUM_CHILDREN_12 NUM_CHILDREN_13 NUM_CHILDREN_14 weekly_hrs_t1_focal4 weekly_hrs_t_focal4 housework_t1_focal4 housework_focal4 earnings_t1_focal4 earnings_t_focal4 TOTAL_INCOME_T1_FAMILY_4 TOTAL_INCOME_T_FAMILY4 i.shared_birth_in_yr4_v2 i.partnered4)) NUM_CHILDREN_4
(pmm, knn(5) include (      NUM_CHILDREN_0 NUM_CHILDREN_1 NUM_CHILDREN_2 NUM_CHILDREN_3 NUM_CHILDREN_4 NUM_CHILDREN_6 NUM_CHILDREN_7 NUM_CHILDREN_8 NUM_CHILDREN_9 NUM_CHILDREN_10 NUM_CHILDREN_11 NUM_CHILDREN_12 NUM_CHILDREN_13 NUM_CHILDREN_14 NUM_CHILDREN_15 weekly_hrs_t1_focal5 weekly_hrs_t_focal5 housework_t1_focal5 housework_focal5 earnings_t1_focal5 earnings_t_focal5 TOTAL_INCOME_T1_FAMILY_5 TOTAL_INCOME_T_FAMILY5 i.shared_birth_in_yr5_v2 i.partnered5)) NUM_CHILDREN_5
(pmm, knn(5) include (     NUM_CHILDREN_0 NUM_CHILDREN_1 NUM_CHILDREN_2 NUM_CHILDREN_3 NUM_CHILDREN_4 NUM_CHILDREN_5 NUM_CHILDREN_7 NUM_CHILDREN_8 NUM_CHILDREN_9 NUM_CHILDREN_10 NUM_CHILDREN_11 NUM_CHILDREN_12 NUM_CHILDREN_13 NUM_CHILDREN_14 NUM_CHILDREN_15  weekly_hrs_t1_focal6 weekly_hrs_t_focal6 housework_t1_focal6 housework_focal6 earnings_t1_focal6 earnings_t_focal6 TOTAL_INCOME_T1_FAMILY_6 TOTAL_INCOME_T_FAMILY6 i.shared_birth_in_yr6_v2 i.partnered6)) NUM_CHILDREN_6
(pmm, knn(5) include (    NUM_CHILDREN_0 NUM_CHILDREN_1 NUM_CHILDREN_2 NUM_CHILDREN_3 NUM_CHILDREN_4 NUM_CHILDREN_5 NUM_CHILDREN_6 NUM_CHILDREN_8 NUM_CHILDREN_9 NUM_CHILDREN_10 NUM_CHILDREN_11 NUM_CHILDREN_12 NUM_CHILDREN_13 NUM_CHILDREN_14 NUM_CHILDREN_15   weekly_hrs_t1_focal7 weekly_hrs_t_focal7 housework_t1_focal7 housework_focal7 earnings_t1_focal7 earnings_t_focal7 TOTAL_INCOME_T1_FAMILY_7 TOTAL_INCOME_T_FAMILY7 i.shared_birth_in_yr7_v2 i.partnered7)) NUM_CHILDREN_7
(pmm, knn(5) include (   NUM_CHILDREN_0 NUM_CHILDREN_1 NUM_CHILDREN_2 NUM_CHILDREN_3 NUM_CHILDREN_4 NUM_CHILDREN_5 NUM_CHILDREN_6 NUM_CHILDREN_7 NUM_CHILDREN_9 NUM_CHILDREN_10 NUM_CHILDREN_11 NUM_CHILDREN_12 NUM_CHILDREN_13 NUM_CHILDREN_14 NUM_CHILDREN_15    weekly_hrs_t1_focal8 weekly_hrs_t_focal8 housework_t1_focal8 housework_focal8 earnings_t1_focal8 earnings_t_focal8 TOTAL_INCOME_T1_FAMILY_8 TOTAL_INCOME_T_FAMILY8 i.shared_birth_in_yr8_v2 i.partnered8)) NUM_CHILDREN_8
(pmm, knn(5) include (  NUM_CHILDREN_0 NUM_CHILDREN_1 NUM_CHILDREN_2 NUM_CHILDREN_3 NUM_CHILDREN_4 NUM_CHILDREN_5 NUM_CHILDREN_6 NUM_CHILDREN_7 NUM_CHILDREN_8 NUM_CHILDREN_10 NUM_CHILDREN_11 NUM_CHILDREN_12 NUM_CHILDREN_13 NUM_CHILDREN_14 NUM_CHILDREN_15     weekly_hrs_t1_focal9 weekly_hrs_t_focal9 housework_t1_focal9 housework_focal9 earnings_t1_focal9 earnings_t_focal9 TOTAL_INCOME_T1_FAMILY_9 TOTAL_INCOME_T_FAMILY9 i.shared_birth_in_yr9_v2 i.partnered9)) NUM_CHILDREN_9
(pmm, knn(5) include ( NUM_CHILDREN_0 NUM_CHILDREN_1 NUM_CHILDREN_2 NUM_CHILDREN_3 NUM_CHILDREN_4 NUM_CHILDREN_5 NUM_CHILDREN_6 NUM_CHILDREN_7 NUM_CHILDREN_8 NUM_CHILDREN_9 NUM_CHILDREN_11 NUM_CHILDREN_12 NUM_CHILDREN_13 NUM_CHILDREN_14 NUM_CHILDREN_15      weekly_hrs_t1_focal10 weekly_hrs_t_focal10 housework_t1_focal10 housework_focal10 earnings_t1_focal10 earnings_t_focal10 TOTAL_INCOME_T1_FAMILY_10 TOTAL_INCOME_T_FAMILY10 i.shared_birth_in_yr10_v2 i.partnered10)) NUM_CHILDREN_10
(pmm, knn(5) include ( NUM_CHILDREN_1 NUM_CHILDREN_2 NUM_CHILDREN_3 NUM_CHILDREN_4 NUM_CHILDREN_5 NUM_CHILDREN_6 NUM_CHILDREN_7 NUM_CHILDREN_8 NUM_CHILDREN_9 NUM_CHILDREN_10 NUM_CHILDREN_12 NUM_CHILDREN_13 NUM_CHILDREN_14 NUM_CHILDREN_15       weekly_hrs_t1_focal11 weekly_hrs_t_focal11 housework_t1_focal11 housework_focal11 earnings_t1_focal11 earnings_t_focal11 TOTAL_INCOME_T1_FAMILY_11 TOTAL_INCOME_T_FAMILY11 i.shared_birth_in_yr11_v2 i.partnered11)) NUM_CHILDREN_11
(pmm, knn(5) include ( NUM_CHILDREN_2 NUM_CHILDREN_3 NUM_CHILDREN_4 NUM_CHILDREN_5 NUM_CHILDREN_6 NUM_CHILDREN_7 NUM_CHILDREN_8 NUM_CHILDREN_9 NUM_CHILDREN_10 NUM_CHILDREN_11 NUM_CHILDREN_13 NUM_CHILDREN_14 NUM_CHILDREN_15        weekly_hrs_t1_focal12 weekly_hrs_t_focal12 housework_t1_focal12 housework_focal12 earnings_t1_focal12 earnings_t_focal12 TOTAL_INCOME_T1_FAMILY_12 TOTAL_INCOME_T_FAMILY12 i.shared_birth_in_yr12_v2 i.partnered12)) NUM_CHILDREN_12
(pmm, knn(5) include ( NUM_CHILDREN_3 NUM_CHILDREN_4 NUM_CHILDREN_5 NUM_CHILDREN_6 NUM_CHILDREN_7 NUM_CHILDREN_8 NUM_CHILDREN_9 NUM_CHILDREN_10 NUM_CHILDREN_11 NUM_CHILDREN_12 NUM_CHILDREN_14 NUM_CHILDREN_15         weekly_hrs_t1_focal13 weekly_hrs_t_focal13 housework_t1_focal13 housework_focal13 earnings_t1_focal13 earnings_t_focal13 TOTAL_INCOME_T1_FAMILY_13 TOTAL_INCOME_T_FAMILY13 i.shared_birth_in_yr13_v2 i.partnered13)) NUM_CHILDREN_13
(pmm, knn(5) include ( NUM_CHILDREN_4 NUM_CHILDREN_5 NUM_CHILDREN_6 NUM_CHILDREN_7 NUM_CHILDREN_8 NUM_CHILDREN_9 NUM_CHILDREN_10 NUM_CHILDREN_11 NUM_CHILDREN_12 NUM_CHILDREN_13 NUM_CHILDREN_15          weekly_hrs_t1_focal14 weekly_hrs_t_focal14 housework_t1_focal14 housework_focal14 earnings_t1_focal14 earnings_t_focal14 TOTAL_INCOME_T1_FAMILY_14 TOTAL_INCOME_T_FAMILY14 i.shared_birth_in_yr14_v2 i.partnered14)) NUM_CHILDREN_14
(pmm, knn(5) include ( NUM_CHILDREN_5 NUM_CHILDREN_6 NUM_CHILDREN_7 NUM_CHILDREN_8 NUM_CHILDREN_9 NUM_CHILDREN_10 NUM_CHILDREN_11 NUM_CHILDREN_12 NUM_CHILDREN_13 NUM_CHILDREN_14           weekly_hrs_t1_focal15 weekly_hrs_t_focal15 housework_t1_focal15 housework_focal15 earnings_t1_focal15 earnings_t_focal15 TOTAL_INCOME_T1_FAMILY_15 TOTAL_INCOME_T_FAMILY15 i.shared_birth_in_yr15_v2 i.partnered15)) NUM_CHILDREN_15

/* religion t
(pmm, knn(5) include (  i.religion_imp_focal1)) religion_imp_focal0
(pmm, knn(5) include ( i.religion_imp_focal0 i.religion_imp_focal2)) religion_imp_focal1
(pmm, knn(5) include ( i.religion_imp_focal1 i.religion_imp_focal3)) religion_imp_focal2
(pmm, knn(5) include ( i.religion_imp_focal2 i.religion_imp_focal4)) religion_imp_focal3
(pmm, knn(5) include ( i.religion_imp_focal3 i.religion_imp_focal5)) religion_imp_focal4
(pmm, knn(5) include ( i.religion_imp_focal4 i.religion_imp_focal6)) religion_imp_focal5
(pmm, knn(5) include ( i.religion_imp_focal5 i.religion_imp_focal7)) religion_imp_focal6
(pmm, knn(5) include ( i.religion_imp_focal6 i.religion_imp_focal8)) religion_imp_focal7
(pmm, knn(5) include ( i.religion_imp_focal7 i.religion_imp_focal9)) religion_imp_focal8
(pmm, knn(5) include ( i.religion_imp_focal8 i.religion_imp_focal10)) religion_imp_focal9
(pmm, knn(5) include ( i.religion_imp_focal9 i.religion_imp_focal11)) religion_imp_focal10
(pmm, knn(5) include ( i.religion_imp_focal10 i.religion_imp_focal12)) religion_imp_focal11
(pmm, knn(5) include ( i.religion_imp_focal11 i.religion_imp_focal13)) religion_imp_focal12
(pmm, knn(5) include ( i.religion_imp_focal12 i.religion_imp_focal14)) religion_imp_focal13
(pmm, knn(5) include ( i.religion_imp_focal13 i.religion_imp_focal15)) religion_imp_focal14
(pmm, knn(5) include ( i.religion_imp_focal14 )) religion_imp_focal15
*/

= birth_yr i.raceth_fixed_focal i.first_educ_focal i.sample_type rel_start_all, by(SEX) chaindots add(1) burnin(3) rseed(8675309) noimputed augment // dryrun // noisily force  // i.FIRST_BIRTH_YR

;
#delimit cr

// I'm an idiot and somehow the rel dur variables got lost?
merge 1:1 unique_id partner_id using "$temp/PSID_couples_wide_toimpute.dta", keepusing(min_dur max_dur total_rel_dur)
drop if _merge==2
drop _merge

save "$created_data/PSID_births_imputed_wide.dta", replace

// browse unique_id partner_id min_dur max_dur weekly_hrs_t1_focal*

********************************************************************************
**# let's look at some descriptives regarding data distributions
********************************************************************************
// first, reshape long
mi reshape long partnered raceth_focal any_psid_births_t_focal any_psid_births_t_hh any_psid_births_t1_focal any_psid_births_t1_hh FAMILY_INTERVIEW_NUM_ state_fips age_focal AGE_YOUNG_CHILD_ children cohab_est_head college_focal COR_IMM_WT_ CORE_WEIGHT_ COUPLE_STATUS_HEAD_ CROSS_SECTION_FAM_WT_ CROSS_SECTION_WT_ earnings_t_focal earnings_t1_focal earnings_t2_focal educ_focal educ_t1_focal educ_t2_focal employed_focal employed_t1_earn_focal employed_t1_hrs_focal employed_t2_focal first_birth_sample_flag HOUSE_STATUS_ housework_focal housework_t1_focal housework_t2_focal in_sample LONG_WT_ MARITAL_PAIRS_ marital_status_updated MARST_DEFACTO_HEAD_ MARST_LEGAL_HEAD_ moved MOVED_YEAR_ NUM_CHILDREN_ NUM_IN_HH_ rel_status RELATION_ survey_yr relationship_est religion_focal religion_t1_focal religion_t2_focal second_birth_sample_flag second_birth_flag_cons structural_familism TOTAL_INCOME_T_FAMILY TOTAL_INCOME_T1_FAMILY_ TOTAL_INCOME_T2_FAMILY_ weekly_hrs_t_focal weekly_hrs_t1_focal weekly_hrs_t2_focal shared_birth_in_yr ///
, i(unique_id partner_id) j(relationship_duration)

mi convert flong

browse unique_id partner_id relationship_duration weekly_hrs_t_focal housework_focal _mi_miss _mi_m _mi_id

gen imputed=0
replace imputed=1 if inrange(_mi_m,1,10)

// save "created data/PSID_births_imputed_long.dta", replace // this where it saved in HPC, but it's currently 7GB
save "$created_data_large/PSID_births_imputed_long.dta", replace // this where it saved in HPC, but it's currently 7GB

drop if relationship_duration > max_dur

mi update

save "$created_data_large/PSID_births_imputed_long_sample.dta", replace

inspect weekly_hrs_t_focal earnings_t_focal housework_focal weekly_hrs_t1_focal earnings_t1_focal housework_t1_focal if imputed==0
inspect weekly_hrs_t_focal earnings_t_focal housework_focal weekly_hrs_t1_focal earnings_t1_focal housework_t1_focal if imputed==1

tabstat  weekly_hrs_t_focal weekly_hrs_t1_focal earnings_t_focal earnings_t1_focal housework_focal housework_t1_focal religion_focal, by(imputed) stats(mean sd p25 p50 p75)
tab religion_focal imputed, col

twoway (histogram weekly_hrs_t_focal if imputed==0 & weekly_hrs_t_focal<=100, width(2) color(blue%30)) (histogram weekly_hrs_t_focal if imputed==1 & weekly_hrs_t_focal<=100, width(2) color(red%30)), legend(order(1 "Observed" 2 "Imputed") rows(1) position(6)) xtitle("Weekly Employment Hours")
twoway (histogram weekly_hrs_t1_focal if imputed==0 & weekly_hrs_t1_focal<=200, width(2) color(blue%30)) (histogram weekly_hrs_t1_focal if imputed==1 & weekly_hrs_t1_focal<=200, width(2) color(red%30)), legend(order(1 "Observed" 2 "Imputed") rows(1) position(6)) xtitle("Weekly Employment Hours (T1)")
twoway (histogram housework_focal if imputed==0 & housework_focal<=50, width(2) color(blue%30)) (histogram housework_focal if imputed==1 & housework_focal<=50, width(2) color(red%30)), legend(order(1 "Observed" 2 "Imputed") rows(1) position(6)) xtitle("Weekly Housework Hours")
twoway (histogram earnings_t_focal if imputed==0 & earnings_t_focal >=-1000 & earnings_t_focal <=300000, width(10000) color(blue%30)) (histogram earnings_t_focal if imputed==1 & earnings_t_focal >=-1000 & earnings_t_focal <=300000, width(10000) color(red%30)), legend(order(1 "Observed" 2 "Imputed") rows(1) position(6)) xtitle("Annual Earnings")

